- README.md
environment options are not used by `./packages/dev-server/dev-config.ts` if passed as `--opt`, but they correctly work if passed before the command `DB=<mysql|postgres|sqlite> <whateverCommand>`
> feat(doc): Script options ignored

- docs/content/docs/getting-started.md
Because of problems when executing vendure installation on Windows, getting started guide should be updated. 
The installation process needs a specific python version (node-gyp). Installation of **windows-build-tools** ensures this.
> Update getting-started.md because of problems with Windows OS

- admin-ui/src/app/data/data.module.ts
This makes possible to make requests to `https://demo.vendure.io/admin-api` instead of `https://demo.vendure.io:80/admin-api` (`auto` binds the port to the location port number, while `80` would add the port to the host): with this modif, I managed deploying a static site (on AWS S3) pointing to demo vendure API (for the moment)
> fix(api-port): Api port removed from Api request if === 80

- admin-ui/src/app/app.module.ts
This is fixing an issue I found when deploying the static site: bundles fetched were `/admin//i18n-messages/<lang.json>`, provoking an error.
> fix(i18n): Leading slash fot i18n bundles is redundant

- packages/email-plugin/src/default-email-handlers.ts
- packages/email-plugin/src/email-sender.ts
- packages/email-plugin/src/event-listener.ts
- packages/email-plugin/src/handlebars-mjml-generator.ts
- packages/email-plugin/src/noop-email-generator.ts
- packages/email-plugin/src/plugin.spec.ts
- packages/email-plugin/src/plugin.ts
- packages/email-plugin/src/types.ts
This introduces the `from` field to the email plugin config.
It is processed by handlebars as it is `subject`
> feat(email-plugin): Added `from` field to the email config

- docs/content/docs/developer-guide/plugins/extending-the-admin-ui.md
docs: Add 'requirePermission' property in 'Adding new ActionBar buttons' example code, because invisible button.
> docs: Fix 'Adding new ActionBar buttons' example code

- packages/core/src/i18n/messages/en.json
- packages/core/src/i18n/messages/es.json
Hi 👋 
There were missing translations for error about missing default channel from channel service.
Here is related function:
https://github.com/vendure-ecommerce/vendure/blob/987b611fa3a7afc5f70183a773299d9d88f4da0c/packages/core/src/service/services/channel.service.ts#L118
Translations for ES are from google translate but I think it's better than nothing. 
I also think we should have the same amount of messages for both languages, even if not everything is translated because, again, any kind of message is better than nothing ;)
Now in es.json, there are much fewer translations.
Cheers 🥂
> fix(core): add missing translations for default channel not found

- packages/core/src/api/schema/common/currency-code.graphql
I'm currently experimenting with vendure and so far like it quite a lot.
I currently think of migrating an existing e-commerce shop and am now checking whether I can implement all required features. While setting up a demo system I noticed that the swiss currency code is set to `CHW` instead of `CHF`. This is probably because ISO 4217 defines three currency codes for switzerland but `CHF` is the one usually used.
Also I noticed that the name used in the channel settings ("WIR euros") can't be found inside the repository so I'm not sure where to do this change/update.
> fix(core) Fix swiss and congolese currency codes

- packages/ui-devkit/src/compiler/scaffold.ts
**Describe the bug**
When generating the shared extension module the different extension modules are joined together correctly but if one extension contains multiple modules the default `join` inserts commas which results in a compilation error.
**To Reproduce**
Export multiple ngModules from one extension.
EDIT: It's the default behavior in JS: https://jsfiddle.net/kyp8L5bx/
**Expected behavior**
The imports should be joined together with a '' instead of a comma
> fix(ui-devkit) Fix generation of shared module file

- packages/core/src/api/api.module.ts
- packages/core/src/api/config/configure-graphql-module.ts
- packages/core/src/config/config.service.mock.ts
- packages/core/src/config/config.service.ts
- packages/core/src/config/default-config.ts
- packages/core/src/config/vendure-config.ts
- packages/create/templates/vendure-config.hbs
- packages/dev-server/dev-config.ts
BREAKING CHANGE: The graphql-playground for the Shop and Admin APIs are now turned off by default, and the Apollo server debug option is also set to false by default (it was formerly true). You can manually configure these values using the VendureConfig.apiOptions object.
> feat(core): Added playground and debug config for graphql apis

- packages/core/src/service/helpers/utils/channel-aware-orm-utils.ts
- packages/core/src/service/helpers/utils/get-entity-or-throw.ts
- packages/core/src/service/services/product-variant.service.ts
This pull request tries to implement the idea mentioned in https://github.com/vendure-ecommerce/vendure/issues/328#issuecomment-623290422.
Step one and two are done at the same time as before as one is required to do the join anyway.
I wasn't able to think of a case where performing the two steps separately would require less memory but I might be missing something.
In addition to the ideas mention I added the eager option to getEntityOrThrow to further decrease the memory required. Is this okay or should this parameter be implemented differently / i.e. a separate function be added with this functionality?
> perf(core): Improved performance of validateVariantOptionIds

- packages/core/src/config/config.service.mock.ts
- packages/core/src/config/config.service.ts
- packages/core/src/config/default-config.ts
- packages/core/src/config/vendure-config.ts
- packages/core/src/service/services/administrator.service.ts
- packages/create/package.json
- packages/create/src/gather-user-responses.ts
- packages/create/src/types.ts
- packages/create/templates/vendure-config.hbs
- packages/testing/src/simple-graphql-client.ts
This pull requests modifies the core, testing, and create packages to allow the user to specify superadmin credentials during and after app creation.
The core package was modified to add superadmin credentials fields to the config object and to allow reading of the credentials from config in the administrator service, while in the create package new prompts asking for credentials while providing default values were added.
The testing package was modified to allow the `SimpleGraphQLClient` class to access credentials from the `vendureConfig` argument.
This pull request closes issue #279 .
> feat(core,testing,create): Enable users to specify superadmin credentials

- packages/core/src/service/helpers/utils/channel-aware-orm-utils.ts
Apparently findByIdsInChannel didn't actually filter for the ids passed to it.
> fix(core): Fix findByIdsInChannel to take ids into account

- packages/core/src/config/custom-field/custom-field-types.ts
- packages/core/src/config/default-config.ts
- packages/core/src/entity/custom-entity-fields.ts
- packages/core/src/entity/register-custom-entity-fields.ts
- packages/core/src/entity/shipping-method/shipping-method.entity.ts
> feat(core): Enable custom fields on ShippingMethod entity

- packages/core/src/config/shipping-method/shipping-calculator.ts
I realize that when I fix the issue #398 with the PR #407 I forget to add `undefined` in `calculate` function of the shipping calculator. So to fix that I create a `CalculateShippingFnResponse` type to use in all responses in this file.
> refactor: Update shipping calculator typing

- packages/asset-server-plugin/src/s3-asset-storage-strategy.ts
Allows a more generic use of the S3 standard. 
As an example, it enables the usage of [MinIO](https://min.io/), an open source object storage which can be useful in several ways, e.g. for local development using storage buckets or as a part of a Kubernetes cluster.
It can also be used as a gateway to other object storages like Google Cloud Storage or Azure. This way, Vendure supports several new storage engines without the need for custom asset storage strategies.
Example usage:
```typescript
storageStrategyFactory: configureS3AssetStorage({
bucket: process.env.STORAGE_BUCKET || 'default',
credentials: {
accessKeyId: process.env.STORAGE_ACCESSKEY || 'default',
secretAccessKey: process.env.STORAGE_SECRETKEY || 'default',
},
nativeS3Configuration: {
endpoint: process.env.STORAGE_ENDPOINT || …
```
> feat: Extended S3Config to accept aws-sdk configuration properties

- packages/core/e2e/order-channel.e2e-spec.ts
- packages/core/src/api/resolvers/entity/order-entity.resolver.ts
- packages/core/src/entity/order/order.entity.ts
- packages/core/src/service/services/order.service.ts
Related to issue #440 .
Still have an issue where the order is not saved under the default channel. I am however using the ChannelService.AssignToCurrentChannel() method.
> Making Orders ChannelAware #440

- packages/admin-ui/src/lib/core/src/shared/components/asset-file-input/asset-file-input.component.ts
**STR:**
1.  custom-built admin-ui, `ts-node compile-admin-ui.ts`:
```
import { compileUiExtensions } from '@vendure/ui-devkit/compiler';
import path from 'path'
compileUiExtensions({
outputPath: path.join(__dirname, 'dist/admin-ui'),
extensions: [{
translations: {
ru: path.join(__dirname, 'translations/ru.json'),
}
}],
}).compile!()
```
2. connect admin-ui plugin in `vendure-config.ts`:
```
AdminUiPlugin.init({
app: {
path: path.join(__dirname, 'admin-ui/dist')
},
...
});
```
3. open admin web page from Safari browser 13.0.5
**ART:** 
-  blank page
- https://stackoverflow.com/questions/56137343/angular-not-working-on-safari-browser-but-working-well-on-other-browsers
**ERT:**
- page opens as usual
> bug(admin-ui): Asset drag/drop support in safari

- docs/content/docs/developer-guide/authentication.md
On Vendure 0.16.0, now `findCustomerUser` requires `ctx` parameter
> fix(docs): update findCustomerUser call

- docs/content/blog/2020-10-08-announcing-vendure-0-16-0/index.md
The migration to channel aware customers query was not correct. Fixed.
Added mandatory ctx object to new style "this.connection.getEntityOrThrow()".
Additionally after generating migration script I had to update the queries to update gaps in old data. Here with these bold values:
**await queryRunner.query(`UPDATE "order" SET "state"='Delivered' WHERE "state"='Fulfilled'`, undefined);**
await queryRunner.query(`ALTER TABLE "fulfillment" ADD "state" character varying NOT NULL **DEFAULT 'Delivered'**`, undefined);
_So maybe you want to include those updates in guide as well._
> Fixes in migration guide

- packages/admin-ui/src/lib/core/src/components/user-menu/user-menu.component.scss
For small devices in conjunction with long username (which is usual case as we use emails as usernames) the header causes big overflow that renders ui almost unusable.
As fix in this PR I hid username altogether as it's not crucial information.
_If the display of currently logged-in admin is wanted, I would include it in main menu for sm devices._
> Fix overflow that made website unusable on sm devices

- packages/admin-ui/i18n-coverage.json
- packages/admin-ui/src/lib/order/src/components/order-list/order-list.component.ts
- packages/admin-ui/src/lib/static/i18n-messages/cs.json
- packages/admin-ui/src/lib/static/i18n-messages/de.json
- packages/admin-ui/src/lib/static/i18n-messages/en.json
- packages/admin-ui/src/lib/static/i18n-messages/es.json
- packages/admin-ui/src/lib/static/i18n-messages/pl.json
- packages/admin-ui/src/lib/static/i18n-messages/pt_BR.json
- packages/admin-ui/src/lib/static/i18n-messages/zh_Hans.json
- packages/admin-ui/src/lib/static/i18n-messages/zh_Hant.json
- move "Cancelled" from _Open_ to _Closed_.
- add new "Shipped" - reasoning behind is that "Shipped" orders are not of interest to shop managers-by this time they done their part with fulfilling the order. Keeping "Partially Shipped" and "Partially Fulfilled" in _Open_, as there is still some actions to be done. Even if need of manual marking of "delivered", they are still not as important as orders that are awaiting/in the processing.
Improvement here would also be that these presets would be configurable by devs to match an use-case exactly.
> Refine new order list filters

- README.md
I stumbled across this when installing, because I got back to the root folder after the 5. step.
> fix(docs): Fix path in readme to make installation process more clear

- packages/elasticsearch-plugin/src/elasticsearch.service.ts
When searching elastic with an empty search term, elastic does not return a score. When requesting the score in the GraphQL API, an error is thrown. This PR replaces the score with 0 in case there is none.
> fix(elasticsearch): Default score 0

- packages/elasticsearch-plugin/src/indexer.controller.ts
- packages/elasticsearch-plugin/src/options.ts
This simple change allows us to add translated CustomMappings to Products and ProductVariants in Elastic
> feat(elasticsearch): LanguageCode support in CustomMappings

- packages/core/src/service/helpers/order-modifier/order-modifier.ts
- packages/core/src/service/services/order.service.ts
We encountered a drastic performance decrease when updating order item quantities by large numbers. 
Example: adding 100, 100 and 900 items:
Also, CPU and memory spike up:
(note: chart not related to the previous image with requests)
After investigation, saving a list of entities (order items) seems to be a bottleneck. Two improvements are suggested:
* The loop containing a `.save()` now stores the new order items in an array, saving all at once later on.
* Saving all items at once via `.save(orderItems)` did not improve performance drastically. It appears TypeORM has a performance [issue](https://github.com/typeorm/typeorm/issues/1115) saving bulk items via `.save()`. Using the query builder however improves the performance.
Some execution times (in ms) between `.save()` and `.insert()` …
> perf: improve order quantity update performance

- packages/core/package.json
- packages/core/src/entity/order-item/order-item.entity.ts
- packages/core/src/service/helpers/order-modifier/order-modifier.ts
- packages/core/src/service/services/order.service.ts
- packages/dev-server/load-testing/graphql/shop/adjust-order-line.graphql
- packages/dev-server/load-testing/scripts/very-large-order3.js
- yarn.lock
See https://github.com/vendure-ecommerce/vendure/pull/703#issuecomment-777959555.
* Adds missing `.execute()`.
* Fixes unknown order item ids after insert.
* Insert or override on update for applying price changes.
The tests in the previous PR most likely didn't fail as the request returns the correct results. However subsequent requests make the new order items "disappear" again as they weren't stored correctly due to the missing `.execute()`.
> perf: improve order quantity update performance (part 2)

- packages/asset-server-plugin/src/s3-asset-storage-strategy.ts
This allows us to pass more native S3 options. 
For example, we are using `{ partSize: 1024 * 1024 * 100 }` to specify no `resumable` uploads are allowed to AWS/GCS for files smaller than 100MiB. Without this config, uploads tend to fail for files larger than a few megabyte.
> feat(asset-server): Add S3 upload options in configuration

- packages/core/src/config/default-config.ts
- packages/core/src/config/vendure-config.ts
- packages/core/src/service/services/order.service.ts
Yet another quite small generic feature to limit orders per order line. 
Could be a choice to not have this in the core, just a suggestion.
> feat(core): Add order line limit to Vendure configuration

- packages/email-plugin/src/email-processor.ts
- packages/email-plugin/src/email-sender.ts
- packages/email-plugin/src/plugin.spec.ts
- packages/email-plugin/src/types.ts
@michaelbromley - is this what you had in mind? The default options are still instantiated if nothing is passed to the plugin via `EmailPluginOptions`. For a developer to replace these items, they would simply need to create a class that implements `EmailSender` (which I extracted into an interface and renamed the original to `DefaultEmailSender`) and a class that implements EmailGenerator and pass instances of them into the plugin at the VendureConfig level. 
Please let me know if there is a more preferable way to go about this. Thanks!
> feat: Added custom sender and generator option to emailPlugin config

- packages/core/src/api/api.module.ts
- packages/core/src/api/config/configure-graphql-module.ts
- packages/core/src/config/default-config.ts
- packages/core/src/config/vendure-config.ts
Our goal with this PR is to use packages like [https://www.npmjs.com/package/graphql-depth-limit](url), to prevent large queries from bringing down the server.
> feat(core): Allow to pass validationRules to shop and admin GraphQL API

- packages/core/src/common/types/adjustment-source.ts
- packages/core/src/config/promotion/actions/buy-x-get-y-free-action.ts
- packages/core/src/config/promotion/conditions/buy-x-get-y-free-condition.ts
- packages/core/src/config/promotion/index.ts
- packages/core/src/config/promotion/promotion-action.ts
- packages/core/src/config/promotion/promotion-condition.ts
- packages/core/src/entity/promotion/promotion.entity.ts
- packages/core/src/service/helpers/order-calculator/order-calculator.ts
- packages/core/src/service/services/promotion.service.ts
#732
Had a bit of trouble trying to get the typing right. I started with `PromotionActionConfig['conditions']` being an array of string values. But with the array I couldn't get the typing to interpret the string values as literal, while still handling an empty/missing conditions array correctly.
So I made it more analogous to the ConfigArgs object. The difference being that for now in the ConditionConfig, there's not really any useful data to be passed in the values, it's mostly the keys we use. There's a `required` field now, but perhaps there is not a lot of use to it. My guess is in most cases the value for `required` will be `true`
So perhaps somebody has a better solution?
> feat(core): add promotion state and promotion action-condition dependency

- packages/core/src/service/services/order.service.ts
When an Order is placed on a certain Channel, Promotions from other Channels are applied as well. Using the PromotionService, the filtering per Channel is automatically applied.
> fix(core): Filter Promotions on Channel before applying to Order

- packages/common/src/generated-shop-types.ts
- packages/common/src/generated-types.ts
- packages/core/e2e/graphql/generated-e2e-shop-types.ts
- packages/core/src/api/schema/common/common-types.graphql
- packages/core/src/service/services/payment-method.service.ts
Closes #738 .
`yarn codegen` failed with an error in auth.e2e-spec.ts (not related to this PR) which I couldn't figure out, so I skipped the generation of admin types and thus something might be missing there. But it seems to build and run fine.
> feat(core): Add name and description fields to eligiblePaymentMethods query

- packages/email-plugin/src/dev-mailbox.ts
Will fix: https://github.com/vendure-ecommerce/real-world-vendure/issues/14
Only `.json` files shall be taken into account.
> fix(email-plugin): Added filename filter for json files

- packages/core/src/service/services/facet-value.service.ts
- packages/elasticsearch-plugin/package.json
- packages/elasticsearch-plugin/src/elasticsearch-resolver.ts
- packages/elasticsearch-plugin/src/elasticsearch.service.ts
- packages/elasticsearch-plugin/src/indexer.controller.ts
- packages/elasticsearch-plugin/src/options.ts
- packages/elasticsearch-plugin/src/plugin.ts
- yarn.lock
As promised, a PR with some performance upgrades for the ElasticSearch plugin.
- Returned FacetValues are now filtered based on Channel since those became ChannelAware. I fixed this by making the `findByIds()` function ChannelAware, which makes this function not consistent with the others. I'm open to suggestions here.
- We expanded the connectivity check on startup to retry a configurable amount of times. Reason for this is that hosting platforms perform maintenance tasks that often involve restarting nodes. ElasticSearch is much slower in startup than Vendure, and hence the worker would start without subscribing to the indexing jobs.
- During indexing, the Product and its variants are queried separately. This greatly reduces memory usage of the worker.
- Indexing itself is simplified a …
> feat(elastic): improve indexing performance

- packages/core/src/service/services/asset.service.ts
Shall fix (#844)
- Added optional `customFields?: { [key: string]: any }` to `createAssetInternal` signature and passed it in `Asset` constructor. 
- Added `await this.customFieldRelationService.updateRelations(ctx, Asset, input, result);` in `create` function
> fix(core): Fixed missing customField input for assets (#844)

- packages/core/e2e/configurable-operation.e2e-spec.ts
- packages/core/src/service/helpers/config-arg/config-arg.service.ts
Implements non-empty checks for different input types of required config-args. Solves #855 
What's not in this commit: Checks for validity of input for actual configured type.
> fix(core): Handle different input types in validateRequiredFields()

- packages/admin-ui/src/lib/order/src/components/order-payment-card/order-payment-card.component.ts
Display refund's metadata on admin-ui order details. Solves #874
> fix(admin-ui): Display refund metadata

- packages/email-plugin/src/plugin.ts
When using the EmailPlugin devMode without having specified the route for the mailbox makes the Vendure server crash: added option to description to clarify usage.
> fix(email-plugin): Docs missing parameter route on devMode example

- packages/core/src/service/services/collection.service.ts
Changes in this pull request will improve the performance of apply-collection-filters job.
I noticed that we use only variants ids before we reassign `collection.productVariants` in `CollectionService.applyCollectionFiltersInternal`.
Based on experiments the performance of the query in `CollectionService.getCollectionProductVariantIds` method will be 8x faster.
> perf(core): Improve performance of apply-collection-filters job

- packages/core/e2e/shop-order.e2e-spec.ts
- packages/core/src/api/resolvers/shop/shop-order.resolver.ts
- packages/core/src/config/config.module.ts
- packages/core/src/config/default-config.ts
- packages/core/src/config/order/order-by-code-access-strategy.ts
- packages/core/src/config/vendure-config.ts
Implements #922 
This commit adds an option to disable the default 2h time window for guests to retrieve their orders through the `orderByCode` query.
Security considerations: The DefaultOrderCodeStrategy [generates the Code](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/common/generate-public-id.ts#L19) from 33 different characters and is 16 characters long – which makes 33^16 different possible codes (~2*10^24). Collisions are highly unlikely, especially if a request limiter is being used.
This commit is non-breaking. Additionally one db query is saved.
> feat(core): Option to enable permanent anonymous access to orderByCode

- packages/core/src/app.module.ts
- packages/core/src/bootstrap.ts
- packages/core/src/common/types/common-types.ts
- packages/core/src/config/default-config.ts
- packages/core/src/config/vendure-config.ts
Implements [#934 ](https://github.com/vendure-ecommerce/vendure/issues/934)
We currently have no way to control the body parser applied to the global middleware.
This commit would let us configure it the same way we already configure  copple of the NestApplicationOptions using Vendure config.
> feat(core): Allow to configure body parser

- docs/content/developer-guide/payment-integrations/index.md
`success: false` seems to be limited to SettlePaymentErrorResult now.
> docs: Correct settlePayment function return type

- packages/admin-ui/src/lib/settings/src/components/channel-detail/channel-detail.component.html
fix(admin-ui): fix Safari dropdown auto-select
Relates to #1036 . This commit adds an extra empty option tag to default shipping and taxing zones, in order for Safari to select these and not the first real option.
> fix(admin-ui): fix Safari dropdown auto-select (#1036)

- packages/core/src/service/services/asset.service.ts
> allow custom host id when creating new entity for orderable assets

- packages/elasticsearch-plugin/src/elasticsearch.service.ts
- packages/elasticsearch-plugin/src/indexer.controller.ts
- packages/elasticsearch-plugin/src/indexing-utils.ts
Fixes #1106
Make sure elasticsearch-js client is instantiated with the clientOptions
> fix(elasticsearch-plugin): Elasticsearch Cloud auth is not set during re-indexing

- packages/core/src/service/services/collection.service.ts
> fix(core): fix collection update event generation

- docs/content/storefront/shop-api-guide.md
`eligibleShippingMethods` is a [query](https://www.vendure.io/docs/graphql-api/shop/queries/#eligibleshippingmethods) and not a mutation as per docs. Currently the link doesn't take the user to the right page.
> fix(docs): Fix GraphQL operation type for eligibleShippingMethods in Shop API guide

- packages/core/src/common/configurable-operation.ts
Fix issue #1221,  Remove an argument of an already saved payment method causes runtime error
> Fix issue #1221,  Remove an argument of an already saved payment method causes runtime error

- packages/core/src/service/services/asset.service.ts
The stream will not be recognized as ReadStream if used createReadStream from the regular FS package. 
This will fix it.
> Fixes stream not being instance of ReadStream

- packages/core/src/plugin/default-search-plugin/indexer/indexer.controller.ts
When indexing many items with multiple channels and languages, the postgresql will throw an error because of parameter limit to exceed. 
Setting Chunk size will fix the problem.
> Fixed batch size error on Postgresql

- packages/admin-ui/src/lib/catalog/src/components/product-assets/product-assets.component.ts
If no assets array is set via the `assets` input of the ProductAssetsComponent this error is thrown:
```
ERROR TypeError: Cannot read properties of undefined (reading 'slice')
at ProductAssetsComponent.set assetsSetter [as assetsSetter] (vendure-admin-ui-catalog.js:7092)
at setInputsForProperty (core.js:10960)
at elementPropertyInternal (core.js:10004)
at Module.ɵɵproperty (core.js:14787)
at RecipeDetailComponent_Template (recipe-detail.component.html:61)
at executeTemplate (core.js:9599)
at refreshView (core.js:9465)
at refreshComponent (core.js:10636)
at refreshChildComponents (core.js:9261)
at refreshView (core.js:9515)
```
This pull request fixes this by using an empty array as a fallback.
I can change it to this alternative and more robust implementation if you like this solution …
> Fix(admin-ui): Fix error if no array of assets is provided

- packages/core/src/api/resolvers/admin/tax-rate.resolver.ts
As per discussion on Slack:
> `TaxRateResolver.taxRates()` demands `ReadTaxRates` or `ReadCatalog` permissions for the tax to be displayed. I would expect `ReadProduct` to get the job done too.
> Agreed, the `ReadProduct` should be added to the `Allow` decorator for that field.
`TaxRateResolver.taxRates()` is ultimately called by `VariantPriceDetailComponent`, which is used in the product variant view. A role with "read" permissions to Product should be allowed to access that information in the same vein as `ReadCatalog`.
I have also added a missing `async` to the function definition as it returns a `Promise` like the other queries in the same class.
**NOTE:** I did not update the `taxRate` resolver in a similar fashion because from what I could gather it's only [eventually …
> fix(core): Add Permission.ReadProduct to Allow decorator of TaxRateResolver.taxRates

- packages/admin-ui/src/lib/catalog/src/components/variant-price-detail/variant-price-detail.component.ts
- packages/admin-ui/src/lib/core/src/common/generated-types.ts
- packages/admin-ui/src/lib/core/src/data/definitions/settings-definitions.ts
- packages/admin-ui/src/lib/core/src/data/providers/settings-data.service.ts
As per discussion on Slack:
> `TaxRateEntityResolver.customerGroup()` kicks in to resolve the `TaxRate.customerGroup` field and requires either `ReadCustomer` or `ReadCustomerGroup` permissions. I found it curious that a field resolver needs additional permissions on top of what its parent query (`TaxRateResolver.taxRates()`) does.
Is my assumption to just rely on `ReadProduct` for a full read-only view of products associated to a channel correct or are these added permissions really necessary?
> I think the real issue here is that there is actually no need to even access the `TaxRate.customerGroup` field when listing ProductVariants. I just re-used an existing graphql fragment which is used in the main TaxRate list view. So the solution would be to alter the query to omit that field for …
> fix(admin-ui): Fix tax rate permissions so product variants do not need access to customer groups

- packages/core/src/api/resolvers/admin/tax-category.resolver.ts
This is closely related to #1258 and something I missed when testing read-only permissions.
`TaxCategoryResolver.taxCategories()` is also ultimately called as part of the product view flow; in this case, by `ProductDetailComponent`. It already allows `ReadCatalog` so it makes sense to allow `ReadProduct` as well.
> fix(core): Add Permission.ReadProduct to Allow decorator of TaxCategoryResolver.taxCategories

- README.md
- packages/core/src/config/catalog/collection-filter.ts
Just fixing a couple doc issues I came across:
`README.md`:
* The default port number for the dev server is 3000 and not 4200 as defined in [shared-constants.ts](https://github.com/vendure-ecommerce/vendure/blob/5f5f767e145938959a0f17d3abe1a25091c6779b/packages/common/src/shared-constants.ts#L5)
* `fragments` as opposed to `fragements`
`collection-filter.ts`
* Link to `default-collection-filters.ts` currently returns a 404. Updating the path to the correct one
> fix(docs): Fix typos in README and collection-filter link comment

- packages/admin-ui/src/lib/core/src/app.component.ts
Related issue: #1290 
This fix will allow users to use `ctrl+u` and `cmd+u` on macs.
Documentation: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey
> Fix(admin-ui): cmd+u shortcut on macOS

- packages/core/src/config/promotion/promotion-action.ts
fixes #1322 
Looking at the code the cause is somewhat obvious, the action's state matcher uses `Object.keys` for a conditions' array which messes up `pick()` function. This code reverts to using `map()` with code.
> fix(core): Order promotions passing state correctly

- packages/core/src/config/entity-id-strategy/uuid-id-strategy.ts
Updates the jsdoc of uuid-id-strategy to configure via `vendure-config/entityOptions/entityIdStrategy` instead of the deprecated `vendure-config/entityIdStrategy` property.
> docs(core): Updates UuidIdStrategy jsdoc to resolve vendure-config/entityIdStrategy deprecation

- docs/content/plugins/extending-the-admin-ui/_index.md
- docs/content/plugins/extending-the-admin-ui/using-other-frameworks/_index.md
- packages/core/src/api/schema/admin-api/collection.api.graphql
- packages/core/src/api/schema/shop-api/shop.api.graphql
Fixing a few very minor doc typos I came across while writing my first plugins:
* `docs/content/plugins/extending-the-admin-ui/_index.md`: "is _built_ with" as opposed to "is _build_ with"
* `docs/content/plugins/extending-the-admin-ui/using-other-frameworks/_index.md`: the `reactUiExtension` import is not used in the code snippet so not needed
* `packages/core/src/api/schema/admin-api/collection.api.graphql`: "specified" as opposed to "speicified"
* `packages/core/src/api/schema/shop-api/shop.api.graphql`: same as above plus `PaymentAuthorized` (as per [order state values](https://github.com/vendure-ecommerce/vendure/blob/ce147dc13e139be6d734016f43f7abeed9fac8d9/packages/core/src/service/helpers/order-state-machine/order-state.ts#L12))  instead of `PaymentApproved`
> fix(docs): Fix minor Admin UI and GraphQL doc typos

- packages/core/src/config/default-config.ts
- packages/core/src/config/vendure-config.ts
- packages/core/src/job-queue/job-queue.service.ts
Adds a `prefix` option to the jobQueue configuration. Solves: https://github.com/vendure-ecommerce/vendure/issues/1350
> feat(core): Added a job queue name prefix as a config option

- packages/admin-ui/src/lib/core/src/components/main-nav/main-nav.component.scss
- packages/admin-ui/src/lib/core/src/providers/i18n/i18n.service.ts
@michaelbromley I found another problem related to the navigation elements that I have missed in my last pull request (#1362). Here is an example based on a ridiculously long word (left before the fix, right after the fix):
Mobile:  
I had to change the `lang` attribute of the `html` element to match the current language code to make `hyphens` work correctly (https://css-tricks.com/almanac/properties/h/hyphenate/):
> Note that hyphens is language-sensitive. Its ability to find break opportunities depends on the language, defined in the lang attribute of a parent element. Not all languages are supported yet, and support depends on the specific browser.
> fix(admin-ui): Fix hyphenation of long words

- packages/core/src/api/config/graphql-custom-fields.ts
Relates to #1377. This commit adds an additional check for public/internal customFields on the `OrderAddress` schema type before adding `AddressCustomFields` to it.
> fix(core): Fix OrderAddress type AddressCustomFields error (#1377)

- packages/admin-ui-plugin/build.ts
- Fix `yarn build` if path contains spaces
- Wait until removal of compile dir is done before starting new build
> Enhance build.ts script for admin-ui-plugin

- packages/core/src/config/order/order-item-price-calculation-strategy.ts
as seen in slack, I updated the doc to list all mutations that trigger OrderItemPriceCalculationStrategy
In fact, there are only four of them since the strategy is only triggered if the 3rd optional parameter `updatedOrderLines` is given and only 4 methods provide it
> fix doc for OrderItemPriceCalculationStrategy

- docs/content/getting-started.md
- packages/payments-plugin/package.json
- packages/payments-plugin/src/braintree/README.md
- packages/payments-plugin/src/braintree/types.ts
- packages/payments-plugin/src/mollie/mollie.controller.ts
- packages/payments-plugin/src/stripe/README.md
- packages/payments-plugin/src/stripe/constants.ts
- packages/payments-plugin/src/stripe/index.ts
- packages/payments-plugin/src/stripe/raw-body.middleware.ts
- packages/payments-plugin/src/stripe/stripe.controller.ts
- packages/payments-plugin/src/stripe/stripe.handler.ts
- packages/payments-plugin/src/stripe/stripe.plugin.ts
- packages/payments-plugin/src/stripe/stripe.resolver.ts
- packages/payments-plugin/src/stripe/stripe.service.ts
- packages/payments-plugin/src/stripe/types.ts
- yarn.lock
Complements #1087.
The goal of this PR is to add Stripe integration to `@vendure/payments-plugin` using the [Custom payment flow ](https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements) and [Payment Intents API](https://stripe.com/docs/payments/payment-intents).  A rough, high-level sequence diagram of a successful payment for an order can be seen below, which aids in explaining the key components in more detail:
* `stripe.plugin.ts`
Actual plugin class.
* `stripe.resolver.ts`
Contains the resolver for the `createStripePaymentIntent` Shop API mutation, which requires an active order in the current session.
* `stripe.service.ts`
Provides methods to interact with Stripe via the `stripe` Node library, most importantly, the creation of a payment intent for the active …
> feat(payments-plugin): Add Stripe integration

- packages/core/src/api/resolvers/admin/global-settings.resolver.ts
Currently, if you use GraphQL interface on relational custom field, admin-ui will not be able to query all fields, that is presented in this interface. This pull request fixes global config generation.
> fix(core): Support usage GQL interface on relational custom field

- packages/core/src/service/index.ts
Added the order-testing service to the index.ts to be able to use it in the implementation.
Fixes #1469
> fix(core): Add order-testing service to index.ts

- packages/core/e2e/database-transactions.e2e-spec.ts
- packages/core/e2e/fixtures/test-plugins/transaction-test-plugin.ts
- packages/core/src/api/decorators/request-context.decorator.ts
- packages/core/src/api/middleware/transaction-interceptor.ts
- packages/core/src/common/constants.ts
- packages/core/src/connection/transaction-wrapper.ts
- packages/core/src/connection/transactional-connection.ts
- packages/core/src/event-bus/event-bus.ts
**The problem**
Current architecture of transaction and context guarantees that if one of operation inside of transaction block fails, whole transaction aborts. To bound queries to transaction we use getRepository(ctx, Entity) function, where ctx is the context which bound to transaction:
```
executeInTransaction(ctx, ctx => {
await getRepository(ctx, Entity).update(...) // op1
await getRepository(ctx, Entity2).delete(...) // op2
... lots of another ops
})
```
If op2 fails, then op1 and other ops in the transaction block aborts, that is what developer actually expects.
Say you have this code:
```
executeInTransaction(ctx, ctx => {
op1 = getRepository(ctx, Entity).update(...)
op2 = getRepository(ctx, Entity2).delete(...)
await Promise.all([op1, op2, op3, opN...])
})
```
This way developer …
> fix(core): Copy context on transaction start. Do not allow to run queries after transaction aborts.

- packages/core/src/api/resolvers/admin/order.resolver.ts
- packages/core/src/service/services/order.service.ts
**The problem**
Currently, it is impossible to have a  orderService.modifyOrder() call along with other logic in the same transaction, because internally modifyOrder() manages transaction itself. Slack thread: https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1650625231400079
**The solution**
Move transaction logic outside of this function to resolver.
**Alternative solution**
Use nested transaction (save points). This is more elegant solution, but it requires typeorm update to 0.2.45 version (0.2.41 current), and introduces changes in core module. This is long-term issue which will be resolved later.
> fix(core): Manage transactions outside of order modify function

- packages/core/src/job-queue/subscribable-job.ts
**The problem**
Currently, getting polling updates through `job.updates()` is not always possible, because of a mistake in operator `distinctUntilChanged`. Current logic is to ignore updates if `progress` OR `state` is equal to previous value. So if your job do not update progress, you will not receive any update through polling. Also this bug spawns a memory leak, because `takeUntil` operator placed after `distinctUntilChanged`
**The solution**
Change operator to ignore updates if `progress` AND `state` are equal to previous values.
> fix(core): Job update doesn't emit if progress didn't changed

- packages/admin-ui/src/lib/core/src/public_api.ts
- packages/core/src/config/payment/dummy-payment-method-handler.ts
- packages/core/src/config/payment/example-payment-method-handler.ts
- packages/core/src/config/payment/payment-method-eligibility-checker.ts
- packages/core/src/config/payment/payment-method-handler.ts
- packages/core/src/service/services/payment-method.service.ts
- packages/core/src/service/services/payment.service.ts
Currently there is not way to get payment method for which handler and eligibility checker called. This PR adds such ability.
> feat(core): Pass payment method to handler and eligibility checker

- packages/elasticsearch-plugin/src/api/elasticsearch-resolver.ts
This [commit](https://github.com/vendure-ecommerce/vendure/commit/152e64b) updated the permissions for the `pendingSearchIndexUpdates` query for `SearchResolver` and `AdminFulltextSearchResolver` but missed `AdminElasticSearchResolver`. This PR aims to fix that problem.
> fix(elasticsearch-plugin): Fix permissions for pendingSearchIndexUpdates query

- packages/core/src/common/error/errors.ts
- packages/core/src/connection/transactional-connection.ts
**Motivation**
Having getRepository() with optional RequestContext argument is not safe:
```
withTransaction(ctx, ctx => {
await getRepository(ctx, User).create(...)
await getRepository(Administrator).create(...) <--- A serious mistake here, this query will be out of transaction.
});
```
Therefore current way to get repository from connection is error prone: it's simple to forget to pass context. 
**Solution**
Deprecate getRepository(Entity) function without RequestContext argument. Introduce `getOuterRepository()` function to enforce explicitly usage.
```
withTransaction(ctx, ctx => {
await getRepository(ctx, User).create(...)
await getRepository(Administrator).create(...) <--- A deprecation warning thrown by IDE. Developer should pay an attention
// If this is intended behavior, …
```
> feat(core): Deprecation of getRepository without context argument

- packages/core/e2e/database-transactions.e2e-spec.ts
- packages/core/e2e/fixtures/test-plugins/transaction-test-plugin.ts
- packages/core/package.json
- packages/core/src/connection/transaction-subscriber.ts
- packages/core/src/connection/transaction-wrapper.ts
- packages/core/src/event-bus/event-bus.ts
- yarn.lock
**Motivation**
Nested transactions (savepoints) may be highly helpful in case if the developer wants to perform complex logic blocks with sql-queries:
```
transaction1 {
1. Create new customer
2. transaction2 {
1. Change product quantity
2. Add new products
} catch() {}
3. Assign new customer to group
}
```
Currently, there is no way to perform nested transactions, because typeorm (0.2.41 does not support savepoints) as well as vendure allows only one-level transactions at `startTransaction()` function. In the example above, everything in transaction2 will be performed in the same database transaction as everything in transaction1. If something bad happened in transaction2 we will not be able to perform step 3 (assign new customer to group), cause database transaction is already rolled …
> feat(core): savepoints support (nested transactions).

- packages/core/src/bootstrap.ts
- packages/core/src/config/logger/vendure-logger.ts
- packages/dev-server/dev-config.ts
Our application uses a custom [Winston](https://github.com/winstonjs/winston) logger implementing `VendureLogger`, which behind the scenes sends logs to New Relic but whose output is similar to `DefaultLogger`. At first, we had quite a few log entries with an "[undefined]" prefix because, in different places, messages are logged without a `context` parameter. `DefaultLogger` handles this scenario by internally defining a "VendureServer" default context, which is overridden by the worker process to use "VendureWorker" instead. However, this logic is not flexible and only applies to instances of `DefaultLogger`.
The idea is to define `setDefaultContext` as an optional method of `VendureLogger` - therefore not resulting in breaking changes - and update `bootstrapWorker` to call the function …
> feat(core): Declare setDefaultContext in VendureLogger

- docs/content/plugins/extending-the-admin-ui/admin-ui-theming-branding/_index.md
- packages/admin-ui/README.md
- packages/admin-ui/scripts/compile-styles.js
- packages/admin-ui/src/lib/core/src/components/app-shell/app-shell.component.scss
- packages/admin-ui/src/lib/core/src/components/main-nav/main-nav.component.scss
- packages/admin-ui/src/lib/static/styles/_variables.scss
- packages/admin-ui/src/lib/static/styles/global/_sass-overrides.scss
- packages/admin-ui/src/lib/static/styles/styles.scss
- packages/admin-ui/src/lib/static/styles/ui-extension-theme.scss
- packages/ui-devkit/src/compiler/scaffold.ts
- packages/ui-devkit/src/compiler/types.ts
- packages/ui-devkit/src/compiler/utils.ts
Although the Admin UI supports theming via CSS custom properties, there's a vast amount of styling in Clarity that, despite being customisable via Sass variables, is not accessible to Vendure developers. The design system framework is undergoing a transformation period where, slowly, Sass variables are being converted to CSS custom properties, but there are still [hundreds](https://github.com/vmware-clarity/ng-clarity/blob/689a572344149aea90df1676eae04479795754f3/projects/angular/src/utils/_variables.clarity.scss) of styling rules that are controlled by the CSS preprocessor. At the moment, there's no way to properly configure theming of such rules as intended on the Admin UI; instead, new declarations targeting specific elements must be added to `globalStyles`, often times using the …
> feat(admin-ui,ui-devkit): Support Clarity Sass variable overrides

- packages/admin-ui/tsconfig.json
- packages/admin-ui/tsconfig.lib.json
Prevents build error `Property 'flat' does not exist on type 'string[][]'`
```shell
✔ Bundling to UMD
- Writing package metadata
✔ Writing package metadata
✔ Built @vendure/admin-ui/core
- Compiling with Angular in legacy View Engine compilation mode.
✖ Compiling with Angular in legacy View Engine compilation mode.
src/lib/catalog/src/components/product-variants-editor/product-variants-editor.component.ts:492:98 - error TS2550: Property 'flat' does not exist on type 'string[][]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later.
492                 const allUsedOptionIds = p.variants.map(v => v.options.map(option => option.id)).flat();
~~~~
src/lib/catalog/src/components/product-variants-editor/product-variants-editor.component.ts:495:2 …
```
> fix(admin-ui): Lib es2019 so ts understands array.flat

- packages/core/e2e/default-search-plugin.e2e-spec.ts
- packages/core/src/plugin/default-search-plugin/search-strategy/mysql-search-strategy.ts
- packages/core/src/plugin/default-search-plugin/search-strategy/postgres-search-strategy.ts
- packages/core/src/plugin/default-search-plugin/search-strategy/search-strategy-common.ts
- packages/core/src/plugin/default-search-plugin/search-strategy/search-strategy-utils.ts
- packages/core/src/plugin/default-search-plugin/search-strategy/sqlite-search-strategy.ts
**Motivation**
Say you have a product with EN translation. You use default search plugin, and two languages are available: EN, AZ.
Searching product with EN languageCode gives you a product, but when you search AZ, results are empty. 
My expectations around this, to be product available in AZ search, but it should be in default translation, which is determined by channel's `defaultLanguageCode `, so in EN.
**Solution**
Use `LEFT JOIN` clause on the same table, to join identical records but with default language code, if preferred language code and default one are different. 
Example generated query:
```sql
SELECT
"si"."languageCode" AS "si_languageCode",
"si"."enabled" AS "si_enabled",
"si"."productName" AS "si_productName",
"si"."productVariantName" AS "si_productVariantName", …
```
> fix(default-search-plugin): Language fallback

- packages/core/src/service/helpers/order-state-machine/order-state-machine.ts
Fixes this: https://github.com/vendure-ecommerce/vendure/issues/1735
Slack thread: https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1661264397433399
In case of spreading an empty array into query builder, typeorm leaves an empty brackets in clause: `IN ()`, which is interpreted by database as a syntax error. To accomplish that, an additional check added.
> fix(core): Transition from AddingItems to custom state with an empty order lines

- packages/core/src/service/services/product-variant.service.ts
**Motivation**
I'm using an overriden version of `createOrUpdateProductVariantPrice` in my project, but since this is not correctly used on update, custom behavior does not apply.
**Solution**
Just use existing function on update
> refactor(core): use existing function to update product variant price

- packages/email-plugin/src/event-handler.ts
- packages/email-plugin/src/plugin.spec.ts
As discussed on Slack earlier, this feature allows to set the languageCode of an email manually instead of taking it from the context.
> feat: Allow to override email language

- packages/core/src/plugin/default-search-plugin/search-strategy/mysql-search-strategy.ts
When you uncheck `Group by product`  in Products view we have this MySQL Error (with red notification in admin interface):
`ERROR 1052 (23000): Column 'productVariantId' in group statement is ambiguous`
This is the generated SQL Query:
```sql
SELECT MIN(`si`.`productId`), MIN(`si`.`productVariantId`), GROUP_CONCAT(`si`.`facetValueIds`) AS `facetValues`, 1 as score, BIT_OR(`si`.`enabled`) AS `productEnabled` FROM `search_index_item` `si` LEFT JOIN `search_index_item` `sil` ON              `si`.`channelId` = `sil`.`channelId` AND `si`.`productVariantId` = `sil`.`productVariantId` AND `si`.`productId` = `sil`.`productId` AND `si`.`productAssetId` = `sil`.`productAssetId` AND `si`.`productVariantAssetId` = `sil`.`productVariantAssetId`             AND `si`.`languageCode` != …
```
> fix(core): 'productVariantId' in group statement is ambiguous

- packages/core/src/config/order/changed-price-handling-strategy.ts
- packages/core/src/config/order/order-item-price-calculation-strategy.ts
- packages/core/src/service/services/order-testing.service.ts
- packages/core/src/service/services/order.service.ts
**Motivation**
Say you want to sell first two order items of the same order line for free. To be able to do this, you need an order instance to get an access to other order lines.
**Solution**
Just pass order as an argument to strategies. It's available at every call of strategies methods.
**Alternatives**
Not sure, whether it would work, but it's theoretically possible to get active order from context, but it's just an extra operation, which could be eliminated by passing order from the outside.
> feat(core): Pass order as an additional argument to strategies

- packages/core/src/service/index.ts
Added the translator service to the index.ts to be able to use it in the implementation.
Will allow it to be imported in `@vendure/core` instead of `@vendure/core/dist/service/helpers/translator/translator.service`
> fix(core): Export translator.service from core

- packages/elasticsearch-plugin/src/indexing/indexer.controller.ts
**Reduces the size of the product object during the indexing**
See issue #1837 for more context
To give more context, here is an analysis made with the Datadog profiler tool. Before the optimisation:
After, we are on a more moderate consumption:
> fix(elasticsearch-plugin): Indexing product - reduce object memory size

- packages/core/src/config/promotion/actions/order-fixed-discount-action.ts
Reference: https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1665539143010169
Check the channel `pricesIncludeTax` flag to determine if the upper bounds on a order fixed discount should be tax inclusive.
> fix(core): Order fixed discount considers channel pricesIncludeTax

- packages/payments-plugin/src/stripe/stripe.controller.ts
The Stripe webhook handler does not return a 200 status code response for `payment_intent.payment_failed` events as per [official docs](https://stripe.com/docs/webhooks#acknowledge-events-immediately). This PR fixes that behaviour, which was initially [flagged on Slack](https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1668154455407779).
> fix(payments-plugin): Return 200 on Stripe payment failed event

- packages/email-plugin/src/nodemailer-email-sender.ts
- packages/email-plugin/src/types.ts
Has the advantage of having a sending rate to prevent hitting limits at AWS SES and is officially supported by nodemailer
https://nodemailer.com/transports/ses/
Would be great, if this could be included. Would save us eventual future headaches with send limits of AWS.
> Add email plugin transport options for AWS SES

- packages/ui-devkit/package.json
- packages/ui-devkit/scaffold/tsconfig.json
Fixes #1859 by updating the scaffolding to match the use of `es2019` in the Admin UI's `tsconfig.json`.  This can be be validated by creating a simple plugin with UI extensions, which will use `compileUiExtensions` from the `ui-devkit` and will have some value for `outputPath`.  When that `outputPath` does not contain the `admin-ui` files (i.e, the first time you run it or if you delete the directory that has already been placed there), then it will be copied from the `ui-devkit`'s scaffolding folder.  Before this change, the scaffolding would be copied with `es2017`, which would lead to the error described in #1859.  After this change, the scaffolding will be copied with `es2019`, which would allow for successful compilation.
> Fix(UI devkit) update scaffolding to use correct eslib

- packages/core/src/api/resolvers/admin/channel.resolver.ts
- packages/core/src/api/resolvers/admin/global-settings.resolver.ts
- packages/core/src/service/services/channel.service.ts
Our need is to retrieve a list of channels by id
```
const { items } = await this.findAll(ctx, {
filter: {
id: { in: input.channelIds },
},
})
```
This PR standardize the findAll function of ChannelService, by accepting a list query options and relations, and returning a paginated list.
> feat(core)!: Improve channel service findAll

- packages/core/src/service/services/order.service.ts
Added additional sort order to orderService.findOne query to avoid changing sort order of orderLines if they are created at the exact same time. 
resolves #1903
> Added additional sort order to orderService.findOne query

- packages/elasticsearch-plugin/e2e/elasticsearch-plugin.e2e-spec.ts
- packages/elasticsearch-plugin/src/api/api-extensions.ts
- packages/elasticsearch-plugin/src/elasticsearch.service.ts
- packages/elasticsearch-plugin/src/options.ts
Access to customProductVariantMappings and customProductMappings independently from groupByProduct by adding two new fields - customProductVariantMappings and customProductMappings.
This PR don't break current GQL scheme, just expand it.
We always use `groupByProduct=true`, because our product can have a lot of variants and we don't want to spam our listings of rather similar items. 
Current logic of elasticsearch plugin select the best productVariant attributes after applying filters (through facets values). But this logic is not applied to customMapping - i can't select customProductVariantMappings when i have `groupByProduct=true`. Real case - we have customProductVariantMapping `allAssets` with all image of variant. I want to apply filter `color=blue` and get grouped by product result …
> feat(elasticsearch-plugin): Independently access to customMappings

- packages/core/src/api/schema/admin-api/asset-admin.type.graphql
- packages/core/src/api/schema/common/asset.type.graphql
Enable to retrieve tags on asset for the shop API
* remove the `admin-api` specificity
* add `tags` on common asset type
> feat(admin,shop): enable tags on assets for shop api

- packages/core/src/config/auth/native-authentication-strategy.ts
- packages/core/src/entity/user/user.entity.ts
- packages/core/src/service/helpers/external-authentication/external-authentication.service.ts
- packages/core/src/service/services/auth.service.ts
- packages/core/src/service/services/user.service.ts
The existing way to load User during auth stage have side effects that clears AuthMethod.userId in database.
This PR shows a possible fix.
Is there some TypeORM config/annotation that could fix this cleanly?
> Auth changes to fix external and native interoperability issues

- packages/ui-devkit/src/compiler/scaffold.ts
- packages/ui-devkit/src/compiler/types.ts
- packages/ui-devkit/src/compiler/utils.ts
Given the composable and extensible nature of Vendure, a monorepo codebase where each package encapsulates a custom plugin is most likely a common practice. Often times, different plugins that include Admin UI extensions share similar behaviour/UX and could depend on the same set of custom Angular components, services, etc. However, considering how Admin UI extensions are compiled - the `extensionPath` directory gets copied as is to the output and is "self-contained" so to speak - referencing code outside the folder and, more importantly, modules declared in other extensions is tricky and unintuitive. Sure, you can give `id`s to `AdminUiExtension`s and use relative imports but that requires knowledge of the inner workings of `ui-devkit` and is a brittle approach as the implementation …
> feat(ui-devkit): Support module path mappings for UI extensions

- packages/payments-plugin/src/stripe/stripe-order-process.ts
- packages/payments-plugin/src/stripe/stripe.handler.ts
- packages/payments-plugin/src/stripe/stripe.plugin.ts
- packages/payments-plugin/src/stripe/types.ts
Fixing Stripe plugin docs to properly reference the host of the webhook to be created - refer to [this Slack thread](https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1674384816161209) for more information. Additionally, I deleted a couple unused imports and took the freedom to remove a file that was introduced as part of [this commit](https://github.com/vendure-ecommerce/vendure/commit/6e320cc8b4aee5ed7158655cc292aa93def8e0d9#diff-438dac4bcf33db60b21f01b448a20d18f1981ffe1f24bce2624381d2bfb0009a) but is not used anywhere. Perhaps a leftover?
> fix(payments-plugin): Fix Stripe plugin docs to reference the correct webhook host

- packages/admin-ui/src/lib/core/src/data/providers/interceptor.ts
When [`loginUrl`](https://www.vendure.io/docs/typescript-api/admin-ui-plugin/admin-ui-config/#loginurl) is configured for a custom Admin UI, the app should redirect the user to that URL on GraphQL 403 errors and not to the built-in `/login` route. This PR fixes that behaviour - a couple notes:
* The `redirectTo` query string param is not appended to the URL to keep things simple, as `loginUrl` itself can have query string parameters, be a relative path, etc, and the custom login page would require logic similar to `LoginComponent` to decode the redirect URL.
* Code to display an error notification is skipped since the app is terminated once the user is redirected.
> fix(admin-ui): Redirect to loginUrl if configured on Forbidden GraphQL error

- packages/ui-devkit/src/compiler/scaffold.ts
- packages/ui-devkit/src/compiler/types.ts
- scripts/docs/typescript-docs-parser.ts
As custom UI extensions mature, a Vendure developer might want to write unit tests or perhaps [Storybook stories](https://storybook.js.org/docs/react/writing-stories/introduction) and choose to colocate them with the corresponding component. Currently, UI Devkit copies **everything** inside the `extensionPath` directory, which could also bring unintended files to the output.
Allow developers to optionally specify files within their UI extension to be skipped during the copy process.
* Update `@vendure/ui-devkit` to support a new optional `exclude` property in `AdminUiExtension` objects, which takes a string array and works the exact same way as [TypeScript's `tsconfig.json` counterpart](https://www.typescriptlang.org/tsconfig#exclude).
* Update `typescript-doc-parser.ts` to support …
> feat(ui-devkit): Add "exclude" option to UI extensions

- packages/core/e2e/auth.e2e-spec.ts
- packages/core/e2e/customer.e2e-spec.ts
- packages/core/e2e/graphql/generated-e2e-admin-types.ts
- packages/core/e2e/graphql/shared-definitions.ts
- packages/core/src/api/resolvers/entity/customer-entity.resolver.ts
- packages/core/src/config/auth/native-authentication-strategy.ts
- packages/core/src/service/services/customer.service.ts
- packages/core/src/service/services/user.service.ts
Slack thread [here](https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1674795935727559).
Anyone can be both customer and an administrator using the same email address, since `identifier` is not a unique key in the `user` table. However, some of the existing logic - most notably authentication - ignores that fact and retrieves the first user in the database with a given email without taking user type (Customer vs Admin) or context (Admin vs Shop API) into account. An example of a consequence can be reproduced following the steps below:
* Register a customer and set, say, test@test.com as their email address
* Create a new administrator in the Admin UI using the same email
* Attempt to login to the Admin UI using the credentials of the administrator created above. We always get an …
> fix(core): Fix auth of admin and customer users with the same email

- packages/admin-ui/src/lib/settings/src/components/admin-detail/admin-detail.component.scss
Fix small cosmetic issue on the Administrator detail page when the channel list is too long. As it can be seen below, it overflows the content box and doesn't respect the boundaries of the view. A quick solution is to present a horizontal scrollbar when necessary.
> fix(admin-ui): Fix UI for long channel list tab on Administrator detail page

- docs/content/developer-guide/testing.md
- packages/testing/src/data-population/populate-for-testing.ts
- packages/testing/src/types.ts
Currently, `productsCsvPath` is a required field when [initialising the test server](https://www.vendure.io/docs/developer-guide/testing/#initialize-the-server), regardless whether or not the developer needs product data to begin with. An alternative is to provide a CSV with headers only and not data rows, which is not a big deal but as a matter of convenience it would be nice to skip the property entirely. This PR updates the attribute to be optional.
> feat(testing): Turn productsCsvPath into an optional property for test server initialization

- packages/core/e2e/fixtures/test-plugins/list-query-plugin.ts
- packages/core/e2e/list-query-builder.e2e-spec.ts
- packages/core/src/service/helpers/list-query-builder/list-query-builder.ts
We have a custom field for `Order` that contains a relation list. Something like this:
```ts
{
name: "xxx",
type: "relation",
list: true,
entity: TargetEntity,
readonly: true,
internal: true,
},
```
the relation works great when reading the order directly using the `order(id: "orderId")` query. However when reading it as part of a list via `activeCustomer` the relation is not populated correctly. This is because the current version:
```ts
finalEntity[entry.relation] = entry.entity[entry.relation];
```
doe snot work for nested relations. In our case `entry.relation` would have been `customFields.xxx`.
> Fix: Merge nested relations correctly

- packages/asset-server-plugin/src/s3-asset-storage-strategy.ts
`port` property is not listed in the `AssetServerOptions` (anymore?)
> fix(docs): remove wrong example

- packages/harden-plugin/src/harden.plugin.ts
I noticed that the value of APP_ENV doens't match what's being used in vendure-config.ts or on https://www.vendure.io/docs/deployment/production-configuration/
> fix(docs): make consistent with other docs

- docs/content/_index.md
- docs/content/deployment/deploying-admin-ui.md
- docs/content/developer-guide/authentication.md
- docs/content/developer-guide/configuration.md
- docs/content/developer-guide/customizing-models.md
- docs/content/developer-guide/error-handling.md
- docs/content/developer-guide/importing-product-data.md
- docs/content/developer-guide/shipping.md
- docs/content/developer-guide/taxes.md
- docs/content/developer-guide/testing.md
- docs/content/developer-guide/translations.md
- docs/content/developer-guide/uploading-files.md
- docs/content/developer-guide/vendure-worker.md
- docs/content/plugins/_index.md
- docs/content/plugins/extending-the-admin-ui/_index.md
- docs/content/plugins/plugin-architecture/_index.md
- docs/content/plugins/plugin-examples/_index.md
- docs/content/plugins/plugin-lifecycle/index.md
- docs/content/plugins/writing-a-vendure-plugin.md
- docs/content/storefront/building-a-storefront/_index.md
- docs/content/storefront/managing-sessions.md
- docs/content/storefront/order-workflow/_index.md
- docs/content/storefront/shop-api-guide.md
- docs/content/user-guide/customers/index.md
- docs/content/user-guide/orders/_index.md
- docs/content/user-guide/settings/channels.md
- docs/content/user-guide/settings/shipping-methods.md
- docs/content/user-guide/settings/taxes.md
I stumbled upon a few typos and "unnatural" wordings when browsing the Vendure documentation. Here are my corrections.
> Fixed typos in docs

- packages/core/src/api/decorators/transaction.decorator.ts
- packages/core/src/api/middleware/transaction-interceptor.ts
- packages/core/src/connection/transaction-wrapper.ts
- packages/core/src/connection/transactional-connection.ts
The default isolation level in some databases (see e.g. for postgres https://www.postgresql.org/docs/current/transaction-iso.html - `READ COMMITTED` is default) allows several anomalies, leading to incorrect data. https://en.wikipedia.org/wiki/Isolation_%28database_systems%29 for more context (or do some googling).
I think it would make sense to at least easily allow users to opt in to stronger isolation levels, and preferably do so by default (picking a lower isolation level should only be done when really needed and when you understand what you're doing).
This PR aims to achieve the above. Note that I'm not a seasoned typescript developer, and I had some issues with `yarn` in this repo, so I had to bypass the pre-commit hook.
> feat(core): allow specifying transaction isolation level

- packages/payments-plugin/e2e/graphql/generated-admin-types.ts
- packages/payments-plugin/e2e/graphql/generated-shop-types.ts
- packages/payments-plugin/e2e/mollie-dev-server.ts
- packages/payments-plugin/e2e/mollie-payment.e2e-spec.ts
- packages/payments-plugin/src/mollie/graphql/generated-shop-types.ts
- packages/payments-plugin/src/mollie/mollie-shop-schema.ts
- packages/payments-plugin/src/mollie/mollie.controller.ts
- packages/payments-plugin/src/mollie/mollie.handler.ts
- packages/payments-plugin/src/mollie/mollie.plugin.ts
- packages/payments-plugin/src/mollie/mollie.service.ts
closes #2093
It's my first contribution, best to check everything well.
Also didn't know if I had to add an `@since` tag somewhere and is the Breaking change in the commit message correct?
> feat(payments-plugin): mollie plugin make `redirecturl` dynamic

- .eslintrc.js
@michaelbromley @martijnvdbrug I think I found one reason eslint was crashing for the monorepo.
I ran the linting with debug infos and it did correctly apply only changed files. I just picked a random file and completely destroyed the indentation and included a console.log to test. But still even for just two files it took **40 seconds** and even crashed on me with a:
```log
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
So I found a relevant section in the [typescript-eslint docs](https://typescript-eslint.io/linting/typed-linting/monorepos#important-note-regarding-large--10-multi-package-monorepos) - I quote:
> ## Important note regarding large (> 10) multi-package monorepos
> We've had reports that for sufficiently large …
> Change tsconfig resolving of eslint

- README.md
You will receive an error message when executing yarn for the first time: "error Package "" refers to a non-existing file '"/packages/admin-ui/package"'." This note will be of some help to beginners.
> chore: Add a note for first time "yarn"

- packages/payments-plugin/e2e/stripe-metadata-sanitize.e2e-spec.ts
- packages/payments-plugin/e2e/stripe-payment.e2e-spec.ts
- packages/payments-plugin/src/stripe/metadata-sanitize.ts
- packages/payments-plugin/src/stripe/stripe.service.ts
- packages/payments-plugin/src/stripe/types.ts
Relates to [#1935](https://github.com/vendure-ecommerce/vendure/issues/1935). Allow to append extra metadata to Stripe payment intent based on developer needs.
> feat(payments-plugin): Add metadata field to StripePluginOptions

- docs/content/developer-guide/uploading-files.md
I made this change because i was receiving an error based in the documentation for uploading files, files.map is undefined in the context of FileList and according to [FileList Documentation](https://developer.mozilla.org/pt-BR/docs/Web/API/FileList) we should use a for-loop to populate the sent array.
> fix(docs): Change Uploading Files example files.map to Array.from

- docs/content/typescript-api/core-plugins/email-plugin/custom-template-loader.md
- packages/email-plugin/src/email-processor.ts
- packages/email-plugin/src/types.ts
Closes #2242 
Let me know if you'd like to pass more of the `data` object or if you somehow would hard-type the `templateVars`.
> feat(email-plugin): Expose template vars to template loader

- packages/core/src/service/services/user.service.ts
This applies to both admins and regular users.
> fix(core): Delete user sessions & token upon user-deletion

- packages/payments-plugin/src/stripe/stripe.controller.ts
Only search payment methods in the current channel if they have a stripe handler, not all payment methods of all channels.
Fixes #2290
> Fix(payments-plugin): Only find payment methods in the current channel

- packages/core/src/service/services/fulfillment.service.ts
Fixes https://github.com/vendure-ecommerce/vendure/issues/2303
This refactor allows us to get the fulfillmentLine entities with the relations and avoids calling `entityHydrator.hydrate` afterwards, which improves performance.
> refactor(core): Add relations to the getFulfillmentsLinesForOrderLine method

- docs/content/typescript-api/core-plugins/default-search-plugin/default-search-plugin-init-options.md
- packages/core/src/plugin/default-search-plugin/fulltext-search.service.ts
- packages/core/src/plugin/default-search-plugin/types.ts
Fix typo in option searchStrategy
https://docs.vendure.io/typescript-api/core-plugins/default-search-plugin/default-search-plugin-init-options/#searchstategy
> fix(default-search-plugin): Fix typo in option searchStrategy

- packages/admin-ui/src/lib/core/src/common/utilities/create-updated-translatable.spec.ts
- packages/admin-ui/src/lib/core/src/common/utilities/create-updated-translatable.ts
Where is the setting of the defaultValue taken care of? In the backend? Because I can't seem to access defaultValue in the CustomfieldConfig type.
regarding https://github.com/vendure-ecommerce/vendure/issues/2361
> fix: admin UI nullable custom fields

- packages/admin-ui/src/lib/catalog/src/components/create-product-variant-dialog/create-product-variant-dialog.component.html
- packages/admin-ui/src/lib/catalog/src/components/create-product-variant-dialog/create-product-variant-dialog.component.ts
The "price" field has been added to the variation creation modal. Without it, a variation was always created with price 0.
> feat: Added price field on variation dialog modal

- packages/admin-ui/src/lib/order/src/components/order-data-table/order-data-table.component.html
- packages/admin-ui/src/lib/order/src/components/order-table/order-table.component.html
Added custom data table components to the data table on the order detail page per my usecase: https://github.com/vendure-ecommerce/vendure/issues/2353
I was unable to get the dev-server compileUIExtensions to work so this is untested with a custom component defined, but I'm 90% sure it should work.
> feat(admin-ui): Implement custom components in order detail data table

- packages/payments-plugin/e2e/mollie-payment.e2e-spec.ts
- packages/payments-plugin/src/mollie/mollie.service.ts
By default `mollie.methods.list()` lists payment methods for use with the `payments` API. However, the Mollie integration uses the `orders` integration. This resulted in some payment methods, like `Klarna pay later` not being listed.
This PR fixes that by passing `orders` to the mollie function: `mollie.methods.list({resource: 'orders'})`.
> fix(payments-plugin): List missing available Mollie payment methods for orders api

- packages/common/src/normalize-string.spec.ts
- packages/common/src/normalize-string.ts
When importing a product, we resulted in a slug containing a `®` trademark symbol, which is invalid.
Therefore, in this PR, I made sure to remove the trademark symbols from the normalized strings, such as `©`, `®` and `™`.
> fix(slug): Remove trademark symbols from normalized strings

- packages/payments-plugin/e2e/mollie-payment.e2e-spec.ts
- packages/payments-plugin/src/mollie/mollie.service.ts
Quite an impactful fix:
* Somewhere between V1.9 and v2.0.8 the relation `order.payments` got lost, resulting in Klarna Pay Later orders nver transitioning to PaymentSettled
* Without this fix orders stay in PaymentAuthorized, and shop owners never receive their money. Klarna has a policy that payments should be captured within 30 days, after that capturing payments (= receiving money) is not possible anymore.
* A test case is very useful here, but, time... I've added a Todo in the e2e file
> Fix/mollie klarna AutoCapture doesn't work!

- packages/admin-ui/src/lib/core/src/components/app-shell/app-shell.component.ts
- packages/admin-ui/src/lib/core/src/components/notification/notification.component.html
- packages/admin-ui/src/lib/core/src/components/notification/notification.component.ts
- packages/admin-ui/src/lib/core/src/components/theme-switcher/theme-switcher.component.scss
- packages/admin-ui/src/lib/core/src/providers/localization/localization.service.spec.ts
- packages/admin-ui/src/lib/core/src/providers/localization/localization.service.ts
- packages/admin-ui/src/lib/core/src/shared/components/dropdown/dropdown-menu.component.ts
- packages/admin-ui/src/lib/core/src/shared/components/modal-dialog/modal-dialog.component.html
- packages/admin-ui/src/lib/core/src/shared/components/modal-dialog/modal-dialog.component.ts
`ModalDialogComponent` is now supporting dynamic direction (ltr/rtl) based on the `language` & `locale` provided by  `dataService`.
> feat(admin-ui): Add rtl compatibility to some admin-ui components

- packages/payments-plugin/e2e/stripe-payment.e2e-spec.ts
- packages/payments-plugin/src/stripe/raw-body.middleware.ts
- packages/payments-plugin/src/stripe/stripe.controller.ts
This patch is slightly related to the issue [2450](https://github.com/vendure-ecommerce/vendure/issues/2450), but fixes only the crash side of it: 
I've put the last `response.status(HttpStatus.OK).send('Ok')` to the transaction block, otherwise it crashes the backend with the following error: 
```
...
[server] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[server]     at new NodeError (node:internal/errors:387:5)
[server]     at ServerResponse.setHeader (node:_http_outgoing:644:11)
[server]     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
[server]     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:174:12)
[server]     at StripeController.webhook …
```
> fix(payments-plugin): Stripe controller crashes server instance

- packages/payments-plugin/src/mollie/mollie.helpers.ts
- packages/payments-plugin/src/mollie/mollie.service.ts
This PR fixes:
* Only add `Already paid` orderline to Mollie order if it has a value. [See more info here about already paid](https://github.com/vendure-ecommerce/vendure/issues/2026)
:arrow_up: We dont want this.
* Error throwing for multiple Mollie webhooks coming in with status 'paid'. Status update is now idempotent: if Mollie says order is `paid` but Vendure order is already `paymentSettled`, we don't do anything and return 200. (It was throwing an error). This was the error thrown when another `paid` webhook comes in: `Failed to process incoming webhook: "Error adding payment to order A47MESUAJY7NVBHV: ORDER_PAYMENT_STATE_ERROR"`
> fix(payments-plugin): Idempotent 'paid' Mollie webhooks

- packages/admin-ui/src/lib/core/src/core.module.ts
- packages/admin-ui/src/lib/core/src/providers/alerts/alerts.service.ts
The `pending-search-index-updates` executes a query that returns `forbidden` if neither `ReadCatalog`  nor `ReadProduct` permissions are available. This loads to an automatic logout in admin-ui. This change prevents the call by adding a new configuration property to the `configureAlert` method. If any permission passed via `requiredPermissions` exists the alert is being created. 
If not the alert will be registered if at some point the permission is added and `userStatus` updates.
Closes #2456
> fix(admin-ui): Do not load pending search index updates if permissions are insufficient

- docs/docs/guides/storefront/checkout-flow/index.mdx
Fixes minor typo that can cause issue when people copy and paste the code.
> Add Missing Closing Parentheses on TransitionToState Example Mutation

- docs/docs/guides/developer-guide/rest-endpoint/index.md
Adds "that" to improve legibility.
"In this guide we will define a plugin **_that_** adds a single REST endpoint at `http://localhost:3000/products` which returns a list of all products."
> add missing word in docs

- packages/core/src/api/common/configurable-operation-codec.ts
Fixes issue #2019 
Id's were getting JSON stringified when they shouldn't have been. It only worked for integer ids because `JSON.stringify(1) == 1`. For uuids, `JSON.stringify("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX") != "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"`.
Later, when it uses the values in business logic: https://github.com/vendure-ecommerce/vendure/blob/218561f04cbaf738c0f18302b67b1b077a056a7f/packages/core/src/common/configurable-operation.ts#L459-L460 , JSON.parse() is not called on ids.
I can't guarantee this doesn't break anything as the change is in a critical area.
> fix(core): fix configurable operation id decoding when using uuids

- packages/core/src/service/services/collection.service.ts
Fix the : https://github.com/vendure-ecommerce/vendure/issues/2395 issue.
Return the first found collection matching the findBySlug criteria.
To Test :
1. Create 2 channel
2. Create a collection with slug 'test' in the first channel
3. Create a collection with the same slug the the other channel
4. Go to the admin-api playground (or shop-api).
5. Use the `collection` query with the header set to the first channel token -> you get the collection of this channel
6. Do the same with the header set to the other channel -> you should get the other collection (the one corresponding to the channel in the header).
> fix(core): Fix collection findBySlug issue2395 

- packages/admin-ui/src/lib/react/src/react-hooks/use-query.ts
The aim is to export React `useDataService` hook until the PR https://github.com/vendure-ecommerce/vendure/pull/2498 is available in the next minor release
I haven't added any documentation to limit its use because the export is temporary. Tell me if it's necessary
> feat(admin-ui): Export React useDataService hook

- packages/payments-plugin/src/mollie/graphql/generated-shop-types.ts
- packages/payments-plugin/src/mollie/mollie-shop-schema.ts
Adds a missing `status` field to the `molliePaymentMethods` query. This type was previously not typed by Mollie. It is documented however. 
PR on Mollie's API plugin: https://github.com/mollie/mollie-api-node/pull/335
None.
> fix(mollie): Add missing `status` type

- packages/testing/src/test-server.ts
Allow Nest to rethrow errors on e2e tests
[Nest documentation](https://github.com/nestjs/nest/blob/master/packages/common/interfaces/nest-application-context-options.interface.ts#L18)
Before, when an e2e test crashed due to a missing import
After
> test(testing): allow Nest to rethrow errors on e2e tests

- packages/core/src/service/services/order.service.ts
* Apply pricing adjustments against updated order
* See this issue for more details: https://github.com/vendure-ecommerce/vendure/issues/2345#issuecomment-1798147042
> fix(OrderService): apply pricing adjustments against updated order

- docs/docs/guides/developer-guide/plugins/index.mdx
Correct the doc's plugin-example configuration key from `configure` to `configuration`.
> fix(docs): Correct plugin-example configuration key

- packages/ui-devkit/src/compiler/compile.ts
Required exit because the default node handler is removed, and when developing a vendure app it never exits when using ctrl+c
No
> fix(ui-devkit): Add call to exit in sigint handler

- packages/core/e2e/fixtures/test-plugins/list-query-plugin.ts
- packages/core/e2e/list-query-builder.e2e-spec.ts
- packages/core/src/service/helpers/list-query-builder/list-query-builder.ts
fixes #2555
If a list query contained multiple `customFields` relations, only one had been assigned to the target entity. This fix allows storing multiple relations in `customFields` to be fetched.
None
> fix(core): Fix loading multiple customField relations

- .github/pull_request_template.md
For some reason, emojis don't work from templates anymore, you have to use the unicode emojis. And, we definitely need emojis in the PR template
> Emoji fix for pull_request_template.md

- packages/payments-plugin/src/mollie/mollie.service.ts
When a customer pays with Klarna/pay-later, and autocapture is enabled in the Mollie plugin, an error is thrown: `Failed to process incoming webhook: "Unhandled incoming Mollie status 'completed' for order XXXXXXX with status 'AddingItems'"`
However, this should not be an error, because autocapture makes sure the order is transitioned to PaymentSettled.
This is what happens when a customer pays with Klarna and `autocapture=true` in the Mollie plugin:
1. Customer pays with Klarna
2. Webhook `authorized` comes in from Mollie: The order is transitioned to `PaymentAuthorized`
3. Autocapture is triggered: The payment is settled, then the existing payment for the order is settled, transitioning the order to `PaymentSettled`
4. Within 200ms, we receive a webhook from Mollie with status …
> fix(payments-plugin, Mollie): Ignore completed state to prevent unneccesary error throwing

- packages/payments-plugin/src/mollie/mollie.controller.ts
- packages/payments-plugin/src/mollie/mollie.service.ts
The current version of the Mollie plugin executes any actions that are triggered by transitioning to PaymentSettled (order confirmation email, etc) as if it were in the default channel! This PR fixes that. 
[This PR](https://github.com/vendure-ecommerce/vendure/commit/b4524197364be970e293326c03a345fced9d75a7) uses the RequestContext from the Mollie webhook request, but that context shouldn't be used, because it doesn't contain the correct channel:
```diff
// This is wat changed in the PR above
// mollie.controller.ts
- await this.mollieService.handleMollieStatusUpdate({ channelToken, paymentMethodId, orderId: body.id });
+ await this.mollieService.handleMollieStatusUpdate(ctx, { channelToken, paymentMethodId, orderId: body.id });
// mollie.service.ts
- async handleMollieStatusUpdate({ …
```
> fix(payments-plugin): Make Mollie channel aware again!

- e2e-common/vitest.config.bench.ts
- package.json
- packages/core/e2e/default-search-plugin.bench.ts
- packages/core/e2e/default-search-plugin.e2e-spec.ts
- packages/core/package.json
- yarn.lock
Add default search plugin tests:
- Improve and fix tests
- Add benchmark tests
- Vitest [benchmark](https://vitest.dev/guide/features.html#benchmarking-experimental) testing is currently an experimental feature. Test failures are not yet handled properly. However, using the underlying `tinybench` package directly with Vitest e2e tests ensures that failing tests are handled properly.
> test(core): Add default search plugin tests

- packages/common/src/generated-shop-types.ts
- packages/core/src/api/schema/admin-api/product-admin.type.graphql
- packages/core/src/api/schema/common/product.type.graphql
Expose enabled field for product in shop api
> fix(core): expose enabled field for product in shop api

- packages/admin-ui/src/lib/catalog/src/components/collection-detail/collection-detail.component.scss
- packages/admin-ui/src/lib/static/styles/global/_sass-overrides.scss
- packages/admin-ui/src/lib/static/styles/theme/dark.scss
- packages/admin-ui/src/lib/static/styles/theme/default.scss
Tweak the color of the breadcrumbs/links and keep the style of the two breadcrumbs/links consistent. Under the premise of modifying `default.scss` and `dark.scss`, you still need to add values to `_sass-overrides.scss`.
Before:
After:
> chore(admin-ui): Link color tweak

- packages/admin-ui/src/lib/core/src/shared/components/page-header-tabs/page-header-tabs.component.scss
- packages/admin-ui/src/lib/static/styles/theme/default.scss
Vendure blue is great so I did a little color tweak to keep us with this clean feel, without too much color.
Before:
After:
> chore(admin-ui): Tab-bar color tweak

- packages/admin-ui/src/lib/order/src/components/order-payment-card/order-payment-card.component.scss
> fix(admin-ui): Too long transactionId causes style issues

- docs/docs/guides/core-concepts/auth/index.md
Fixes https://github.com/vendure-ecommerce/vendure/issues/1489 where the identifier and emailAddress should be equal. If they are not equal, you will encounter a `no user with id <not found>` error
No breaking change. Docs change only.
N/A
📌 Always:
> docs: identifier and emailAddress should be equal

- docs/content/typescript-api/core-plugins/elasticsearch-plugin/elasticsearch-options.md
- packages/elasticsearch-plugin/src/indexing/indexer.controller.ts
- packages/elasticsearch-plugin/src/options.ts
Added two new variables to limit the amount of data that can be stored in memory during the reindex job
> Products chunk size for each loop iteration when indexing products.
`reindexProductsChunkSize` - default value is 2500
> Index operations are performed in bulk, with each bulk operation containing a number of individual index operations. This option sets the maximum number of operations in the memory buffer before a bulk operation is executed.
`reindexBulkOperationSizeLimit` - default value is 3000
Refs: https://github.com/vendure-ecommerce/vendure/issues/1770
BREAKING CHANGE: This update optimizes memory usage for large amounts of data and applies to products with many variants. With the help of the memory storage limit, memory consumption can be increased or decreased. The …
> perf(Elasticsearch): optimize memory consumption during reindex.

- packages/payments-plugin/src/mollie/mollie.service.ts
In [this PR](https://github.com/vendure-ecommerce/vendure/pull/2657) we introduced order states that can be ingored when a Mollie webhook comes in, but we missed a few: Cancelled, PartiallyDelivered and partiallyShipped
📌 Always:
> fix(payments-plugin): Mollie ignore order states

- packages/admin-ui/src/lib/core/src/data/providers/base-data.service.ts
- packages/admin-ui/src/lib/core/src/data/utils/is-entity-create-or-update-mutation.ts
- packages/admin-ui/src/lib/core/src/data/utils/remove-readonly-custom-fields.spec.ts
- packages/admin-ui/src/lib/core/src/data/utils/remove-readonly-custom-fields.ts
This PR addresses the issue reported in #2680, where product updates were being blocked due to a bug with the variant auto-rename feature. The root cause was identified as incorrect type annotations.
- Corrected type annotations and refactored two utility functions `removeReadonlyCustomFields` &  `removeReadonly`
- Added two tests to handle this case
- `isEntityCreateOrUpdateMutation` function has been moved to a separate file
Null
📌 Always:
> fix(admin-ui): Product variant auto-rename bug #2680

- packages/core/e2e/entity-hydrator.e2e-spec.ts
- packages/core/e2e/fixtures/test-plugins/hydration-test-plugin.ts
- packages/core/src/service/helpers/entity-hydrator/entity-hydrator.service.ts
Fixes #2682
I already described the issue in #2682. The EntityHydrator crashes if a nested relation should be hydrated but the parent is nullable.
📌 Always:
> fix(core): Handle nullable relations in EntityHydrator

- packages/admin-ui/src/lib/core/src/components/breadcrumb/breadcrumb.component.html
The hover-over tooltips didnt work. Now they do. See screenshots. :handshake: 
None
| Before | After |
|--------|--------|
| ![image](https://github.com/vendure-ecommerce/vendure/assets/14810858/5483c2d1-1546-44e0-978e-b9cca0fa0ce9) | ![image](https://github.com/vendure-ecommerce/vendure/assets/14810858/a249b831-69d3-47a1-a990-2a8e4a0f1c41) | 
📌 Always:
> fix(admin-ui): Add missing translation of breadcrumb tooltips

- packages/common/src/normalize-string.spec.ts
- packages/common/src/normalize-string.ts
- packages/core/e2e/collection.e2e-spec.ts
I propose this change to properly replace umlauts and Eszett for German language strings. It replaces `ß` with `ss` and any combining diaeresis `◌̈` with `e`, i.e. `ä` becomes `ae`, `ö` `oe` and `ü` `ue`, which appears to be the SEO-friendliest replacement. This might be incorrect for other languages, as e.g. Finnish seems to replace `ä` with `a` and `ö` with `o`, so it might be sensible to add i18n to this function.
> Properly replace umlauts and Eszett for German lang

- docs/docs/guides/developer-guide/custom-fields/index.md
Fixes the typo in the docs for customfields
Does this PR include any breaking changes we should be aware of? No
📌 Always:
> fix: typo in custom-fields documentation

- packages/cli/src/commands/new/plugin/scaffold/services/service.ts
DeepPartial from typeorm and Vendure/core are different. This causes type issues on update.  Type safe way is to use patchEntity.
📌 Always:
> Update service.ts Type safet for updated Enttity

- packages/core/src/service/services/product-option-group.service.ts
- packages/core/src/service/services/product.service.ts
This upgrade is needed if you want to remove a product with more than 200 variants and 7 languages. If you leave this data in one SQL query, the memory consumption on the server for data processing reaches 10k MB in the test environment more than 800mb. The presented improvement reduces memory consumption to 1-5mb
📌 Always:
> perf(core): upgrade sql requests for more performant memory usage with big datasets

- packages/core/src/service/helpers/entity-hydrator/entity-hydrator.service.ts
- packages/core/src/service/helpers/list-query-builder/list-query-builder.ts
This code includes the same improvements that were added to ListQueryBuilder to optimize database queries and their processing on the server side
* No
📌 Always:
> perf(core): Upgrade EntityHydrator to add more performance

- packages/core/e2e/fixtures/test-plugins/list-query-plugin.ts
- packages/core/e2e/list-query-builder.e2e-spec.ts
- packages/core/src/service/helpers/list-query-builder/list-query-builder.ts
This code bypasses the typeorm bug related to an error in duplicate aliases when linking to a parent table
Related issue: https://github.com/vendure-ecommerce/vendure/issues/2738
* no
📌 Always:
> fix(core): self-referencing relations `Not unique table/alias`

- packages/core/e2e/shop-order.e2e-spec.ts
- packages/core/src/service/services/order.service.ts
Fixes https://github.com/vendure-ecommerce/vendure/issues/2736
No
📌 Always:
> fix(core): Fix stock constraint error for adjustOrderLine when using OrderLine custom fields

- packages/core/e2e/custom-field-relations.e2e-spec.ts
- packages/core/src/api/common/custom-field-relation-resolver.service.ts
Fixes https://github.com/vendure-ecommerce/vendure/issues/2723
The reason was that we are calling `applyVariantPrices` even when the entity is null. And it happens only for `ProductVariant`.
No
📌 Always:
> fix(core): Fix custom field relation for ProductVariant when value is null

- packages/core/src/service/services/channel.service.ts
This is an optimization of the channel-aware update request for Entity. The method offers 3 separate queries without additional data processing by TypeORM. 
1. Get the object without unnecessary links and check that it exists.
2. Make a separate, more optimized query into the ManyToMany table to reduce the amount of data to process
3. Change the save method to `Remove` or `Add` (unbinds, binds) given value from entity relation.
```ts
relation('channels')
.of(entity.id)
.add(newChannelIds) or .remove(existingChannelIds);
```
No
📌 Always:
> perf(core): optimization for assignToChannels method

- packages/admin-ui/src/lib/settings/src/components/channel-detail/channel-detail.component.html
Default Shipping Zone Id is required field. Alert dialog should be danger instead of warning. 
Also translations need to be changed. Instead of "this may cause errors" it should be  "which will cause errors' like the tax alert
NO
📌 Always:
> Update channel-detail.component.html defaultShippingZoneId is Required

- packages/core/src/service/services/product.service.ts
Ran into an issue where an _OptionGroup_ which was already deleted was attempted to be deleted again.
`getEntityOrThrow` inside the `deleteGroupAndOptionsFromProduct` failed the `softDelete` call on _ProductService_.
> fix: product soft delete check deletedAt option group before trying to delete

- packages/core/src/service/helpers/entity-hydrator/entity-hydrator.service.ts
This fix removes all found links that end with `lines.customFields` because now such links cannot be used. If they are present in relations they may not be added to customFields in the queryBuilder because of them.
no
📌 Always:
> fix(core): Remove empty customFields relations from getMissingRelations in entity-hydrator

- packages/core/src/service/helpers/order-splitter/order-splitter.ts
We encountered an issue regarding the absence of shipping methods in the order generated after payment completion. This problem occurred due to the duplication of shipping method items without assigning new IDs to the orderLines that had the shippingLineId attribute.
> Fix missing shipping lines in partial order after payment

- packages/core/src/entity/order/order.entity.spec.ts
- packages/core/src/entity/order/order.entity.ts
- packages/core/src/testing/order-test-utils.ts
This change adds the `taxLines` of the orders surcharges to the `taxSummary`. Fixes #2797.
Since this fix changes the output of the `taxSummary` resolver it could be a breaking change for users which use the `taxSummary` in there storefront.
📌 Always:
> fix(core): Add surcharge taxLines to taxSummary

- packages/core/src/data-import/providers/populator/populator.ts
Adds RequestContext to asset import for collections. 
The populator loads assets into collections. However, the RequestContext is not passed along. This means that if you import collections on any channel that is not default, the assets get assigned to the default channel only.
As a result a channel specific collection import fails because an empty asset array results that is assumed to be non empty, and referenced.
Resolves issue https://github.com/vendure-ecommerce/vendure/issues/2787
I adjusted test on the populate spec and was surprised that even on the 'populating a non-default channel' the test passed without my changes. On further inspection it seems that that test uses the default channel for its work instead of the intended channel-2. So, it seems to be not validating what it's …
> fix asset importer assigns asset on default channel when importing on non default channel

- packages/core/src/service/services/stock-location.service.ts
The Stock Location update method was not updating relation customFields
Refs: #2804
Essentially just a few lines of code added to the `update` function on StockLocation service file. This will allow relation customField entities to be updated along with the StockLocation update. 
Here are the added lines. Instead of just saving, we now save, then update relation then return a promise<StockLocation> off of assertFound
```
await this.connection.getRepository(ctx, StockLocation).save(updatedStockLocation);
await this.customFieldRelationService.updateRelations(
ctx,
StockLocation,
input,
updatedStockLocation,
);
return assertFound(this.findOne(ctx, updatedStockLocation.id));
```
No Breaking Changes, Just additional steps included in `update()` function
N/A
📌 Always:
> fix: Update Relations on Stock Location update

- packages/dev-server/dev-config.ts
- packages/dev-server/docker-compose.yml
This PR changes the Postgres database name and the credentials in the docker compose to be the same as in the `dev-config.ts`
none
📌 Always:
> fix(dev-server): Update postgres credentials in docker compose

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- packages/core/src/api/config/configure-graphql-module.ts
Adds VSCode `settings.json` with an extension recommendation for conventional commits and pre-defined scopes, that are based on the package names.
none
📌 Always:
> chore(repo): Add VSCode recommended extension for conventional commits with pre-defined scopes

- docs/docs/guides/developer-guide/plugins/index.mdx
A typo in the plugins developer guide. The filepath *src/plugins/reviews-plugin/wishlist.plugin.ts* should say *src/plugins/wishlist-plugin/wishlist.plugin.ts*
This PR does not include any breaking changes.
📌 Always:
> Fix filepath typo.

- packages/core/src/bootstrap.ts
In addition to this PR
https://github.com/vendure-ecommerce/vendure/pull/2482
Here is the cookie naming behavior:
- If not setting the authOptions.cookieOptions.name parameter:
-  Both the Admin API and Shop API cookies names will be the default one: 'session'
- If setting the authOptions.cookieOptions.name parameter to something like 'cookie-name':
- Both the Admin API and Shop API cookies names will be the configured one: 'cookie-name'
- If setting the authOptions.cookieOptions.name parameter to something like `{shop: 'cookie-name', admin: 'admin-cookie-name'}`:
- The Admin API cookie name will be 'admin-cookie-name'
-  Shop API cookie name will be 'cookie-name'
- And all the REST endpoints on the `/` route will use the default cookie: 'session' 
-  context: some systems do not support …
> fix(cookie): Use the shop cookie name for default route

- README.md
- packages/create/templates/readme.hbs
Relating to issue: https://github.com/vendure-ecommerce/vendure/issues/2858 I'm adding a troubleshooting section to the README.md for common issues that pop up during installation and I am adding the issue I came across with some troubleshooting tips to deal with it. 
No
📌 Always:
> docs(troubleshooting): Add troubleshooting section to docs

- packages/create/src/helpers.ts
During the bootstrapping process of `@vendure/create`, the `typescript` package is installed as a regular dependency, I moved it to the dev dependencies. 
~~Regarding `dotenv`, it appears it's only used in the CLI, dev server, and in E2E tests for the payments plugin, please let me know if I missed something and it should be kept as a prod dep.~~
No
N/A
> Move `typescript` to dev dependencies

- packages/core/src/event-bus/events/refund-event.ts
- packages/core/src/event-bus/index.ts
- packages/core/src/service/services/order.service.ts
- Create a new event (Refund Event) which has the created type.
- when the orderService.refundOrder() is called, the new RefundEvent gets published.
Ticket: https://github.com/vendure-ecommerce/vendure/issues/2830
📌 Always:
- [ x] I have set a clear title
- [x ] My PR is small and contains a single feature
- [x ] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
> feat(core): Add refund event for refund creation

- packages/core/src/service/helpers/entity-hydrator/entity-hydrator.service.ts
- packages/core/src/service/helpers/entity-hydrator/merge-deep.spec.ts
- packages/core/src/service/helpers/entity-hydrator/merge-deep.ts
Relations could get out of sync during entity hydration. See #2864 for a detailed description and example.
I moved `mergeDeep` out of the service to make testing easier. I think adding an e2e Test for this does not make sense as it would be very hard to control the result order of the hydration database query. So I decided to unit test `mergeDeep` instead.
The only actual change is:
```ts
if (Array.isArray(value)) {
(a as any)[key] = value.map((v, index) =>
this.mergeDeep(a?.[key]?.[index], b[key][index]),
);
} else if (isObject(value)) {
(a as any)[key] = this.mergeDeep(a?.[key], b[key]);
}
```
changed to:
```ts
if (Array.isArray(value) || isObject(value)) {
(a as any)[key] = mergeDeep(a?.[key], b[key]);
}
```
I don't see a case where calling mergeDeep would not work because mergeDeep …
> fix(core): Keep order of nested relations during hydration (#2864)

- docs/docs/reference/admin-ui-api/react-hooks/use-lazy-query.md
- docs/docs/reference/admin-ui-api/react-hooks/use-query.md
- packages/admin-ui/src/lib/react/src/react-hooks/use-query.ts
In the `DataService`, there exists a method to refetch whenever the channel changes.
However, it was not yet possible to use this `refetchOnChannelChange` method in React custom Admin UI pages when using the `useQuery` and `useLazyQuery` hooks.
In this PR, I added an option on those hooks, so that we can refetch the queries whenever the channel changes.
To test it:
1. Compile the `dev-server` with the `custom-admin-ui` extension
2. In the `ReactUi.tsx` file, add the following:
```tsx
const GET_CHANNELS = gql`
query channels {
channels {
items {
id
code
token
}
}
}
`
const channelsResponse = useQuery<any>(GET_CHANNELS, undefined, { refetchOnChannelChange: true })
```
3. Check the network: whenever the channel changes, the query is run again with the new channel token passed in the headers …
> feat(use-query): Enable to refetch on channel change

- docs/docs/reference/admin-ui-api/ui-devkit/compile-ui-extensions.md
- docs/docs/reference/admin-ui-api/ui-devkit/ui-extension-build-command.md
- docs/docs/reference/admin-ui-api/ui-devkit/ui-extension-compiler-options.md
- packages/ui-devkit/src/compiler/compile.ts
- packages/ui-devkit/src/compiler/types.ts
- packages/ui-devkit/src/compiler/utils.ts
Adds support for `pnpm` when building UI extensions. Implements #2876 
📌 Always:
> feat(ui-devkit): Support pnpm to build UI extensions

- packages/core/src/app.module.ts
- packages/core/src/bootstrap.ts
When using split cookies to have different cookie name for the `shop-api` and the `admin-api`, we used to apply the `cookieSession()` middleware globally.
However, [Nest Global Middlewares](https://docs.nestjs.com/middleware#global-middleware) can't be applied to specific routes.
By doing Global Middlewares, the last applied `app.use()` middleware was overriding the above-mentioned ones.
Instead, we have to use [Functional Middlewares](https://docs.nestjs.com/middleware#functional-middleware) for the specific paths we like.
As a consequence, for the case when the user wants to split the cookies, we do not do it in the `bootstrap()` function any longer but instead we do it in the `AppModule.configure()` method, where other middlewares route-specific are already applied.
There is no …
> fix(cookies): Apply split cookie session middleware per route

- packages/create/src/gather-user-responses.ts
- packages/create/src/helpers.ts
- packages/create/templates/vendure-config.hbs
If a db has mandatory ssl when connecting the current @vendure/create fails.
Implemented SSL Option for PostgreSQL
Added SSL option to populate function
fixes #2904 
No
📌 Always:
> fix(create): Supporting SSL enforced PostgreSQL databases

- packages/core/src/app.module.ts
- packages/core/src/bootstrap.ts
In a previous PR, I tried to fix an issue causing some per-route middlewares being broken when using the split cookies for the Admin and Shop APIs.
- #2880 
But since it was released in the `2.2.6`, the cookies split is no longer working at all.
After investigating, it turned out we were still badly applying the per-route middleware:
- We did not set a global middleware in the `bootstrap.ts` file
- We were overriding the per-route middlewares in the `app.modile.ts` file because of the configuration on the `/` route
In this PR, I made sure to:
1. Apply a global cookies middleware, either using the right cookie name:
- If the cookies have to be split, use the `shop` cookie name
- Else, use the shared cookie name if provided
- If not provided, default to `session`
2. Only apply specific …
> fix(cookies): Correctly apply global and per-route middlewares

- packages/core/src/service/helpers/list-query-builder/list-query-builder.ts
This pull request fixes an issue in the `ListQueryBuilder` class where the method `customPropertyIsBeingUsed` did not properly account for nested filters when checking for custom property usage. 
No breaking changes
📌 Always:
> fix(core): Adding usage check of nested custom property filters in ListQueryBuilder

- docs/docs/guides/extending-the-admin-ui/defining-routes/index.md
- docs/docs/guides/extending-the-admin-ui/page-tabs/index.md
- docs/docs/reference/admin-ui-api/routes/register-route-component.md
- packages/admin-ui/src/lib/core/src/extension/components/route.component.ts
- packages/admin-ui/src/lib/core/src/extension/register-route-component.ts
- packages/dev-server/example-plugins/ui-extensions-library/ui/providers.ts
- packages/dev-server/example-plugins/ui-extensions-library/ui/routes.ts
Add `description` and `locationId` to `registerRouteComponent` and `registerReactRouteComponent` so that users can define custom description and page tabs to their custom routes vis the `registerPageTab` API.
no
📌 Always:
> feat(admin-ui): Add location id and description to custom routes

- packages/core/e2e/duplicate-entity.e2e-spec.ts
- packages/core/src/config/entity/entity-duplicators/product-duplicator.ts
When you copy a product, the tax category is not copied, which leads the tax category to default to whatever is the first one.
- Product duplicator now copies tax categories from the source variant
📌 Always:
- [ x] I have set a clear title
- [ x] My PR is small and contains a single feature
- [ x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
- [ x] I have added or updated test cases
- [ x] I have updated the README if needed
> fix(product-duplicator): Copy tax category on variants

- packages/core/src/config/config.module.ts
- packages/core/src/config/config.service.ts
- packages/core/src/config/default-config.ts
- packages/core/src/config/index.ts
- packages/core/src/config/refund/default-refund-process.ts
- packages/core/src/config/refund/refund-process.ts
- packages/core/src/config/vendure-config.ts
- packages/core/src/service/helpers/refund-state-machine/refund-state-machine.ts
- packages/core/src/service/helpers/refund-state-machine/refund-state.ts
- packages/core/src/service/services/order.service.ts
Unlike other state machines, the 'refund state' was previously implemented in a way that made extension impossible without modifying the core. I have modified it to allow for extension
- [Discord](https://discord.com/channels/1100672177260478564/1217663910572724335)
- [Issue](https://github.com/vendure-ecommerce/vendure/issues/2465)
📌 Always:
> feat(core): Modified refundProcess to be extensible

- README.md
This PR fixes broken links in [README.md](https://github.com/vendure-ecommerce/vendure/blob/master/README.md).
Also I added link to [Publish & Install action](https://github.com/vendure-ecommerce/vendure/actions/workflows/publish_and_install.yml) from badge instead of link to image file))
> docs(README): fix broken links

- packages/core/src/service/helpers/entity-hydrator/entity-hydrator.service.ts
Remove a workaround that led to refetching relations in customFields. Prevent refetching of customFields during hydration
Fixes #2696
See #2696. There was some sort of workaround that disabled the check which is in place to prevent reloading the same data over and over. `entity["customFields.xyz"]` will never be set because the data would be in `entity["customFields"]["xyz"]`.
I'm still wondering if there is some edge case that made this workaround necessary but we are running this patch in production for quite some time now and we are using a lot of `customFields`.
None I would be aware of. This might have been a workaround for a bug in typeorm maybe.
📌 Always:
- [x I have set a clear title
> perf(core): Improve hydrator performance for customFields

- packages/email-plugin/src/email-processor.ts
- packages/email-plugin/src/email-send-event.ts
- packages/email-plugin/src/handler/event-handler.ts
- packages/email-plugin/src/types.ts
Added metadata for `EmailSendEvent` and `setMetadata` function on `EmailEventHandler`
Closes #2849 
📌 Always:
> feat(email-plugin): Allow specify metadata for EmailSendEvent

- packages/core/e2e/fixtures/test-money-strategy.ts
- packages/core/e2e/order-promotion.e2e-spec.ts
- packages/core/src/config/promotion/actions/order-line-fixed-discount-action.ts
- packages/core/src/config/promotion/index.ts
- packages/core/src/config/promotion/promotion-action.ts
- packages/core/src/entity/promotion/promotion.entity.ts
- packages/core/src/service/helpers/order-calculator/order-calculator.ts
To address the issue mentioned in the previous PR, I modified the return type of the `execute` method in `PromotionItemAction` to return either a `Number` or `ExecutePromotionActionResult`, allowing the inclusion of `discountMode`.
However, to maintain code consistency, I have added `PromotionLineAction` and adjusted all `PromotionActions` to return a `Number` type.
Other tasks follow the contents of the attached previous PR.
- [Issue](https://github.com/vendure-ecommerce/vendure/issues/2956)
- [Previous PR](https://github.com/vendure-ecommerce/vendure/pull/2964)
📌 Always:
> feat(core): Create PromotionLineAction

- packages/core/src/config/vendure-config.ts
The [requireVerification docs](https://docs.vendure.io/reference/typescript-api/auth/auth-options#requireverification) are conflicting with the [registerCustomerAccount docs](https://docs.vendure.io/reference/graphql-api/shop/mutations#registercustomeraccount)
📌 Always:
> Docs: `requireVerification=true` does accept password

- packages/core/src/service/services/collection.service.ts
I updated the applyCollectionFiltersInternal method to optimize the handling of more variants and also added updating collections only for changed variants if the product has been updated.
Related issue: https://github.com/vendure-ecommerce/vendure/issues/2733
* no
* no
📌 Always:
> perf(core): Refactor applyCollectionFiltersInternal method to improve performance

- packages/admin-ui/src/lib/catalog/src/components/product-detail/product-detail.component.scss
Updated the block height for the Channel block `.channel-assignment`. Because there was a fixed height there, a large number of channels simply did not fit and the button to add new channels was hidden
* no
Before
After
📌 Always:
> fix(admin-ui): Change max height to min height for channel assignment block

- packages/core/src/service/helpers/external-authentication/external-authentication.service.ts
Retrieves or create a user with external identifier
no
📌 Always:
> feat(core): Create a user from external authentication

- packages/core/src/api/common/request-context.ts
- packages/core/src/connection/transactional-connection.ts
This PR includes improvements for connecting to the database if you are using multiple replicas and when you need to connect to Master without using TransactionManager
- No
> feat(core): Add replicationMode for ctx and getRepository

- packages/core/e2e/entity-hydrator.e2e-spec.ts
- packages/core/e2e/fixtures/test-plugins/hydration-test-plugin.ts
- packages/core/src/service/helpers/utils/tree-relations-qb-joiner.ts
Fixes #2899
Postgres truncates long identifiers making them equal if they share the same prefix. For instance if two tables are being joined with a long alias (the names need to be a lot longer in reality) `product_variant_relation_0_relation_1` and `product_variant_relation_0_relation_2` postgres will truncate both aliases to `product_variant_rel` and fail because it's not allowed to have two join statements with the same target alias.
None
📌 Always:
> fix(core): Truncate db aliases if necessary

- packages/core/e2e/order-modification.e2e-spec.ts
- packages/core/src/service/helpers/order-calculator/order-calculator.ts
This PR solves https://github.com/vendure-ecommerce/vendure/issues/3008, where there's an order level discount and we are updating the order to remove an order line by setting the quantity to 0. Currently, it throws a NaN error.
The solution is just to have a fallback of 0, when the `distribution[i]` returns undefined.
should not break existing functionality.
📌 Always:
> Fix: solve a empty order line with discount modification NaN error

- packages/core/src/plugin/default-search-plugin/indexer/indexer.controller.ts
Relates to #3012.
While indexing variants, a product for a specific variant is queried. However, somewhere in the code the channels are being swapped if multiple channels exist, and they are not being swapped back, which is resulting in the product not being found for that channel as they don't exist, which is making the indexing fail. that's why I have added a line in the code that swaps the channels back to the original one at the start of every loop, and a line at the end of the loop.
> fix(default-search-plugin): Fix channels swapping and not swapping back in saveVariants when working with multiple channels

- docs/docs/guides/developer-guide/testing/index.md
Fix incorrect docs for resolving port conflict in e2e test.
No
Just document error fix
📌 Always:
> docs(testing): Fix incorrect docs for resolving port conflict in e2e test.

- packages/admin-ui/src/lib/core/src/shared/components/asset-picker-dialog/asset-picker-dialog.component.ts
- packages/admin-ui/src/lib/core/src/shared/components/asset-preview-links/asset-preview-links.component.ts
- packages/admin-ui/src/lib/core/src/shared/components/assets/assets.component.ts
- packages/admin-ui/src/lib/core/src/shared/components/rich-text-editor/external-image-dialog/external-image-dialog.component.html
- packages/admin-ui/src/lib/core/src/shared/components/rich-text-editor/external-image-dialog/external-image-dialog.component.scss
- packages/admin-ui/src/lib/core/src/shared/components/rich-text-editor/external-image-dialog/external-image-dialog.component.ts
- packages/admin-ui/src/lib/core/src/shared/components/rich-text-editor/prosemirror/plugins/image-plugin.ts
- packages/admin-ui/src/lib/core/src/shared/components/rich-text-editor/prosemirror/prosemirror.service.ts
- packages/admin-ui/src/lib/static/i18n-messages/en.json
- packages/admin-ui/src/lib/static/i18n-messages/pt_PT.json
- packages/admin-ui/src/lib/static/styles/component/prosemirror.scss
- Added functionality to allow the insertion of images from Vendure's Assets Picker into the ProseMirror editor.
- Implemented a restriction in the assets picker to allow only single image selection to support the ProseMirror's image handling capabilities.
No
https://github.com/user-attachments/assets/f3dbdbfe-42fc-4c83-a760-5624c2f3a679
📌 Always:
> (feat): integrate Vendure Assets Picker with ProseMirror and add single image selection

- packages/core/src/config/catalog/default-collection-filters.ts
When a collection uses a `product-id-filter` or a `variant-id-filter` and the selected IDs are empty, it gets assigned to every product or product variant in the catalog. 
No
📌 Always:
> fix: Handle empty state for product and variant id filter of collections

- packages/core/src/service/helpers/verification-token-generator/verification-token-generator.ts
- packages/core/src/service/services/session.service.ts
Check if the type of `authOptions.sessionDuration` and `authOptions.verificationTokenDuration` is `string` before passing the values to the `ms` function for conversion from a string expression to milliseconds (number). If the type is not a string, it is already expected to be milliseconds so can be used right away.
Fixes #3078 
No breaking changes.
Not applicable.
📌 Always:
> Check type of durations before passing to 'ms' function

- packages/payments-plugin/src/stripe/stripe.controller.ts
… Fixes issue #3072
Orders can switch channels (e.g., global to UK store), causing lookups by the original channel to fail. Using a default channel avoids "entity-with-id-not-found" errors. See https://github.com/vendure-ecommerce/vendure/issues/3072
No
NA
📌 Always:
> fix: Use default channel in Stripe webhook calls to reach all orders

- docs/docs/reference/typescript-api/auth/auth-options.md
- packages/core/src/config/vendure-config.ts
- packages/core/src/service/services/session.service.ts
- Support string expressions (as per `zeit/ms`) for `AuthOptions.sessionCacheTTL` just like for `sessionDuration` and `verificationTokenDuration` (conversion result needs to be divided by 1000 to receive seconds)
- Update documentation and jsDoc to better explain how these properties can be supplied as numbers (seconds/milliseconds) or string expressions (as per `zeit/ms`)
No
Not applicable.
📌 Always:
> Enhance AuthOptions.sessionCacheTTL by allowing string expressions (zeit/ms)

- packages/core/src/data-import/providers/importer/importer.ts
Allow overriding Importer methods.
This should allow more customization for the importer
closes #3000
> refactor(core,data-import): Allow overriding importer methods

- packages/core/src/plugin/default-search-plugin/indexer/indexer.controller.ts
This fixes https://github.com/vendure-ecommerce/vendure/issues/3109
-
-
📌 Always:
> fix(core): Do not include deleted variants when indexing productInStock

- packages/dev-server/example-plugins/multivendor-plugin/README.md
This fixes the link in the readme for the example multi-vendor plugin.
No.
📌 Always:
> Fix broken link in example multi-vendor plugin readme

- docs/docs/guides/storefront/active-order/index.mdx
`removeCouponCode`  mutation doesn't give ErrorResult  it only returns Node of type `Order`
No
📌 Always:
- [] My PR is small and contains a single feature
- [] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
> Docs Update : Code example need change

- packages/core/src/api/config/__snapshots__/graphql-custom-fields.spec.ts.snap
- packages/core/src/api/config/graphql-custom-fields.spec.ts
- packages/core/src/api/config/graphql-custom-fields.ts
This fixes #3158.
Previously, the `addActiveAdministratorCustomFields` function, which adds the custom fields for the Administrator entity into the input type for the `updateActiveAdministrator` mutation, would assume that the `UpdateAdministratorCustomFieldsInput` type exists if there are any non-`readonly` custom fields, even if those custom fields are `internal`. This was incorrect, since `internal` custom fields will not appear in mutation input types, any more than ones that are `readonly`. So, the schema produced would reference that input type, causing a crash if it did not exist, which happened every time there were `internal`, non-`readonly` custom fields.
I also added a test to confirm that the `UpdateAdministratorCustomFieldsInput` type is not referenced when the Administrator …
> Fix crash when Administrator has custom field that is `internal` but not `readonly`

- packages/core/src/common/utils.ts
I've been getting errors when following multivendor example due to this function. ID sometimes seems to be `null` type, causing unexpected errors. This PR adds null support for `idsAreEqual` function to prevent this issue.
This PR shouldn't break existing features.
N/A
📌 Always:
> fix(core/utils): Allow null on idsAreEqual function

- .github/workflows/build_and_test.yml
- packages/core/e2e/cache-service-redis.e2e-spec.ts
Redis service was not configured in the GitHub Actions workflow.
> chore: Fix redis cache plugin tests

- packages/admin-ui/src/lib/catalog/src/components/product-variant-quick-jump/product-variant-quick-jump.component.ts
Fixes #3143, in which the product variant quick select menu was always empty. It appears that this was because the Observable that yielded the variants that should be shown in that menu was created with `mapSingle`, but it needed to be unpacked multiple times by the `async` pipe in the component template.
If there is some test case that should be added for it, please let me know.
Nope.
Here it is, working:
📌 Always:
> fix(admin-ui): Fix Variant Quick-Select Menu

- packages/testing/package.json
- packages/testing/src/simple-graphql-client.ts
- packages/testing/src/utils/create-upload-post-data.spec.ts
- packages/testing/src/utils/create-upload-post-data.ts
- packages/testing/vitest.config.mts
In the testing package, Vendure provides a `SimpleGraphQLClient` that has a function called `fileUploadMutation`. This function works for the built-in GraphQL mutations that accept file uploads, but if you add a custom mutation that accepts file inputs, as the [docs](https://docs.vendure.io/guides/developer-guide/uploading-files/#custom-upload-mutations) show you how to do, you will run into problems, since it assumes that it can find the `Upload` inputs in the GraphQL variables just by looking at the first property of each nested object. So, for example, the existing code that creates the FormData body for the upload will go into an infinite loop if there are any string fields before the Upload fields in your GraphQL mutation input. I detailed the problem that I ran into with this in …
> Make test client's `fileUploadMutation` work for more input variable shapes

- packages/admin-ui/src/lib/order/src/order.routes.ts
I got into the issue where I wasn't able to add a custom component to location `order-list` with the `registerPageTab` provider. Found out that the culprit is the router configuration in admin-ui for the order part. Under the more complex paths with subroutes `pathMatch: full` is not used, only on more basic pages like _login_ and _dashboard_.
Issue reference is here: #3173
If a user has the same order ID like the tab name, that could cause a race condition I assume, but I think this would be unlikely.
📌 Always:
> fix(admin-ui): Make registerPageTab work on 'order-list' location (#3173)

- packages/admin-ui/src/lib/core/src/shared/dynamic-form-inputs/dynamic-form-input/dynamic-form-input.component.ts
Please include a summary of the changes and the related issues.
This fix solves the [issue 3093](https://github.com/vendure-ecommerce/vendure/issues/3093) where the output coming from the dynamic form input has the wrong type. This lead to weird behaviour when selecting the options and also issue with updating the record on the admin UI.
My fix consists of overriding the value with the correct type, I'm unsure if this is a acceptable solution, but it does solve the issue.
For example. 
I have a list of options from a custom field that contains numbers like calling code.
The options are meant to be strings of options. so it's configured like this
```typescript
{
name: "supportedNumbers"
type: "string",
label: [{ languageCode: LanguageCode.en, value: "Supported Phone Number" }],
ui: { …
```
> fix: solve incorrect type when dealing with value in list

- packages/core/src/api/schema/admin-api/order.api.graphql
During the refund implementation in my PayPal integration, I noticed that the `RefundOrderInput` can be a little bit confusing for new developers. At first I did not understand how I am able to use the amount instead of the lines, adjustment and shipping properties.
There was no documentation for this specific input, so I reached out to the discord. In my [help thread](https://discord.com/channels/1100672177260478564/1293232023921491999) we came to false conclusions, as we thought it is not possible to just use the `amount` field by itself without `lines` etc.
After some further investigation, I noticed that deprecating the `lines`, `shipping` and `adjustment` fields in the GraphQL schema have no effects on the e2e tests. On this base, I removed those 3 fields and created this PR to make …
> fix(core): Deprecation of `lines`, `shipping` and `adjustment` fields in the `RefundOrderInput` input.

- packages/core/src/service/services/role.service.ts
Previously it returned `role` which was fetched before(!) applying the update. See definition of `role` in line 253 and then the event bus publishing on line 281. I see that `patchEntity` is mutating the existing object instead of cloning which should be fine for the fields, but then the `updatedAt` is wrong since its not being updated by `patchEntity`. Event subscribers that depend on the `updatedAt` timestamp are receiving a wrong `updatedAt` and or other auto-updated columns.
Also removed the reference returned by `pathEntity` to make it visually clear that it actually mutates the object instead of returning a new one. This way its unambigious.
Note: Have not look at many other services where this might also be the case.
Edit: Not going through `findOne` fails the `role.e2e-spec.ts` …
> fix(core): Fix returning stale data in Role Update Event

- packages/core/e2e/order-merge.e2e-spec.ts
- packages/core/src/service/services/order.service.ts
Merging the guest with the existing order delete any products that would be in both orders. A relevant test was missing.
[related issue](https://github.com/vendure-ecommerce/vendure/issues/3153)
Don't think so but we have to ensure it does not affects other merging strategies.
📌 Always:
> fix(core): Fix merging order with conflicting products

- packages/core/e2e/channel.e2e-spec.ts
- packages/core/src/i18n/messages/de.json
- packages/core/src/i18n/messages/en.json
- packages/core/src/service/services/channel.service.ts
Deleting the default channel breaks the entire instance since you cant log in anymore.
Fixes #3157 
AFAIK none.
📌 Always:
> fix(core): Disallow deletion of default channel

- packages/payments-plugin/e2e/stripe-payment.e2e-spec.ts
- packages/payments-plugin/src/stripe/stripe.service.ts
- packages/payments-plugin/src/stripe/types.ts
This pull request allow the application to send the Stripe-Account header that is used to create a direct charge with Stripe Connect https://github.com/vendure-ecommerce/vendure/issues/3183
https://docs.stripe.com/connect/authentication#stripe-account-header
I am not able to determine a breaking change. The implemented features represent new functionality and should have no effect on existing implementations.
📌 Always:
> feat(payments-plugin): Allow use of Stripe-Account header

- packages/payments-plugin/e2e/mollie-payment.e2e-spec.ts
- packages/payments-plugin/e2e/payment-helpers.ts
- packages/payments-plugin/src/mollie/mollie.service.ts
* Check if the given Mollie method is eligible for the current order. Closes #2973
📌 Always:
> feat(payments-plugin): Check for eligibility of Mollie method

- docs/docs/guides/developer-guide/events/index.mdx
A small error I noticed in the Entity Event docs [here](https://docs.vendure.io/guides/developer-guide/events/#entity-events)
`VendureEntityEvent<BlogPost[], BlogPostInputTypes>`
BlogPost shouldnt be defined as an Array here
No
📌 Always:
> docs: Small error in entity events

- packages/admin-ui/README.md
#3226 
Fix ngx-translate and unicode formated messages link on [packages/admin-ui/README.md](https://github.com/vendure-ecommerce/vendure/tree/master/packages/admin-ui) 
📌 Always:
> docs(admin-ui): fix ngx-translate and unicode link

- packages/core/e2e/stock-control-multi-location.e2e-spec.ts
- packages/core/src/config/catalog/default-stock-location-strategy.ts
- packages/core/src/config/catalog/multi-channel-stock-location-strategy.ts
- packages/core/src/config/default-config.ts
- packages/core/src/config/index.ts
- packages/core/src/event-bus/events/stock-location-event.ts
- packages/core/src/event-bus/index.ts
- packages/core/src/service/services/stock-location.service.ts
- packages/payments-plugin/e2e/stripe-payment.e2e-spec.ts
Addresses #2356. 
This PR replaces the default `stockLocationStrategy` with a brand new one. Although technically it means that the default behaviour is different in multi-channel, multi-location setups, this is only because the old default behaviour was very much non-functional in that scenario.
All the e2e tests pass, so for the single-location scenario supported by the old default, this new one behaves identically.
Therefore in the release notes we will just include a note about this, and provide instructions on how to get the old behaviour back in the unlikely event that someone knowingly relied upon it.
📌 Always:
> feat(core): Introduce MultiChannelStockLocationStrategy

- docs/docs/guides/developer-guide/plugins/index.mdx
- packages/dev-server/example-plugins/wishlist-plugin/service/wishlist.service.ts
added await to db query causing the value to be promise and causing server crash
Issue#2868
If you run the `addToWhishlist` mutation twice then the server crashes with the error:
```
if (this.isReleased) throw new QueryRunnerAlreadyReleasedError()
^
QueryRunnerAlreadyReleasedError: Query runner already released. Cannot run queries anymore.
```
in simple words
If the variant is already in the wishlist and you run the mutation again *(trying to add a variant to wishlist when that variant is already in the wishlist)* the server crashes.
No breaking changes.
📌 Always:
> fix(docs): updated docs for wishlist plugin

- packages/admin-ui/src/lib/core/src/shared/components/data-table-filter-presets/data-table-filter-presets.component.html
- packages/admin-ui/src/lib/core/src/shared/components/data-table-filter-presets/data-table-filter-presets.component.ts
Any page that uses data-table2 with presets, when the presets change they lose any query parameters. This includes the currently set "display per page". This can be very frustrating if you use presets to switch quickly between groups of items which number more than 10 because you have to keep moving down and turning it back up.
This fix causes it to keep any existing query parameters except the "filters" and "page" parameters, which are the ones that it uses.
No, just changed behavior
📌 Always:
> feat(admin-ui): Preset filters should preserve query parameters

- packages/payments-plugin/src/mollie/mollie.service.ts
Another fix to prevent false positive error logging for Mollie:
* We log an error when 2 transactions with different ID's in state `Setted` are added to the order
* However, Klarna payments are `Authorized` first, sometimes, with autocapture, the order is marked as placed already, but the attached Payment on the order is still in state `Authorized`. It only happens occasionally, most of the times Vendure is quick enough to update `order.placedAt` and the corresponding `payment.state=settled`. Some race condition somewhere...
This PR fixes that. Should be a patch, but unsure if there will be a patch before 3.1?
📌 Always:
> fix(payments-plugin): False positive error logging fix

- packages/core/src/api/resolvers/entity/order-line-entity.resolver.ts
We experienced an issue with trying to add products to an existing order; when we added a new product which was not previously in the order, the featuredAsset would resolve to an object with an ID and nothing else.  We have this fix locally as a resolver, but it's simple and innocuous enough I thought I'd submit it for your consideration to help others.
If this isn't the right way to do this I apologize; we're still new-ish to this project. Let me know how to do it better and I'll fix it =]
None
N/A
📌 Always:
- (this might not be a bad idea, but I don't know how to reproduce it with a test case)
> fix(core): It is possible for featuredAsset to resolve to {id: ID}

- docs/docs/guides/developer-guide/plugins/index.mdx
While playing with the code I found two bugs. Just a single additional word each. The missing "async" causes a compile time error. The missing "await" is silent.
Nothing breaks. This is a document.
📌 Always:
Changes are so simple I have done them directly from Github.
> Fix two bugs and add "id" for coherency with other examples

- packages/payments-plugin/e2e/stripe-payment.e2e-spec.ts
- packages/payments-plugin/src/stripe/stripe-utils.ts
- packages/payments-plugin/src/stripe/stripe.controller.ts
- packages/payments-plugin/src/stripe/types.ts
#3249 - gracefully handle non-vendure payment intents from Stripe
Included an option for the consumer as this could be a breaking change otherwise, though it seems extremely unlikely. 
📌 Always:
> feat(payments-plugin): Optionally, do not throw if Stripe payment intent doesn't have Vendure metadata

- docs/docs/guides/core-concepts/promotions/index.md
Corrects incorrect parameter and adds a small additional text to clarify the difference between an order action and orderItem action
No
📌 Always:
- [ x] I have set a clear title
- [ x] My PR is small and contains a single feature
- [ x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
> docs(promotion): Minor correction and addition

- packages/core/src/config/entity/entity-duplicators/product-duplicator.ts
Product duplicator now copies variant customFields. Fixes https://github.com/vendure-ecommerce/vendure/issues/3202
- This will start copying variant related customFields when you use the product duplicator with `includeVariants: true`. This could potentially cause unexpected side effects, if your code previously assumed those customFields were not copied.
📌 Always:
- [x ] I have set a clear title
- [ x] My PR is small and contains a single feature
- [ x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
> fix(product-duplicator): Add source variant customFields to duplicated variant

- LICENSE.md
- docs/docs/guides/how-to/publish-plugin/index.mdx
- license/license-faq.md
- license/plugin-exception.txt
Because Vendure uses the GPL v3.0 license, the common interpretation based on GNU FAQ ([single combined program](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins)) would suggest that any plugins must also be GPL licensed.
However, it is our opinion that plugins should not be subject to this restriction. In our opinion, the GPL requirements should apply to the Vendure code itself (i.e., the files in this repo). Plugin code is not typically distributed as a combined program - it is distributed as a stand-alone package that only consumes the public APIs of Vendure.
A good general background on the topic of linking & derived works as applied to the GPL can be found here: [GNU General Public License: Linking and derived works](https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking …
> chore: Add GPL exception for Vendure plugins

- packages/payments-plugin/src/stripe/stripe-utils.ts
This pull request includes a small change to the `currencyHasFractionPart` function in the `stripe-utils.ts` file. The change improves the readability of the code by replacing the `find` method with the `some` method to check for the presence of a fraction part in the currency formatting.
📌 Always:
> fix(payments-plugin): use some instead of find

- packages/common/src/normalize-string.spec.ts
- packages/common/src/normalize-string.ts
The `normalizeString` function doesn't effectively support cases where the replacer itself occurs in the original string.
`My Product - Complete Collection` -> `my-product---complete-collection`
this PR adjusts the normalizer such that the resultant output is `my-product-complete-collection`
(i've taken a [solitary additional upvote](https://github.com/vendure-ecommerce/vendure/discussions/3169) as the go-ahead signal)
Does this PR include any breaking changes we should be aware of? nup
📌 Always:
> fix(common): Better support for slug generation when the replacer occurs in the input string

- packages/core/e2e/cache-service-default.e2e-spec.ts
- packages/core/e2e/cache-service-in-memory.e2e-spec.ts
- packages/core/e2e/cache-service-redis.e2e-spec.ts
- packages/core/e2e/fixtures/cache-service-shared-tests.ts
- packages/core/src/plugin/redis-cache-plugin/redis-cache-strategy.ts
- Fixes silent failures in the redis cache plugin when setting a ttl that is not a multiple of 1000.
- I rounded the ttl to the nearest second, but I could be convinced to either ceil or floor the value.
- Any other redis errors when setting keys should no longer be silent.
- Negative ttls were being coerced to an unsigned int by redis (large positive value), so I added a check.
- Added tests related to these issues
- No known breaking changes
📌 Always:
> Redis cache plugin fixes

- packages/core/src/service/helpers/order-calculator/order-calculator.spec.ts
- packages/core/src/service/helpers/order-calculator/order-calculator.ts
`OrderCalculator#applyOrderPromotions` clears out all existing `DISTRIBUTED_ORDER_PROMOTION`s before testing promotions. `applyOrderItemPromotions` does not currently do the same, the result of which is that when conditions / actions are encountered, previous adjustment data may be present on the line items in question.
My specific use case was when creating a promotion of the type "apply a bulk purchase discount, but only to items that aren't already discounted," e.g. when there are 10+ of a product and they aren't already discounted.
**Without this change**: upon reaching 10 items, the line items become discounted. Upon reaching 11 items, the test for "are there adjustments applied" returns true (the previous adjustment), resulting in the discount being removed. Bump the quantity to 12 …
> fix(core): Clear previous line adjustments before testing order item promotions

- packages/admin-ui/src/lib/core/src/common/utilities/selection-manager.ts
Selection manager was missing support for multiple selection with the mac's command key, causing Mac users unable to select images one by one. since holding control on Mac opens the right click menu on chrome based browsers.
No
📌 Always:
> fix: add support for mac's command key for selection manager

- docs/docs/guides/developer-guide/dataloaders/index.md
- docs/sidebars.js
I had a problem recently with a cart of more than 15 items becoming incredibly slow to load. It turned out to be the n+1 problem. And although it ultimately turned out to be another kind of n+1 issue than I thought, I decided to return to the topic of `dataloaders` and it turns out you can use them through standard `nestjs`
Since dataloaders are an important part of the GraphQL toolbox, but not broadly understood or used, I have added documentation + an example with a re-usable skeleton so people can get around the performance related issues it solves with ease.
No
📌 Always:
- [ x] I have set a clear title
- [x ] My PR is small and contains a single feature
- [ x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
> docs: Description + example of GraphQL dataloader

- package.json
- packages/elasticsearch-plugin/e2e/e2e-helpers.ts
- packages/elasticsearch-plugin/e2e/elasticsearch-plugin.e2e-spec.ts
- packages/elasticsearch-plugin/src/build-elastic-body.spec.ts
- packages/elasticsearch-plugin/src/build-elastic-body.ts
- packages/elasticsearch-plugin/src/options.ts
Minor tweaks to improve the out-of-the-box search results from elastic search.
It was a bit demotivating to see that my search results were worse than with the default plugin, while ES is such a powerful engine. In my case this was due to:
1. Description being just as important as name fields
2. No type tolerance (fuzziness)
Most consumers probably define their own queries, but for those starting with the defaults this gives them a better experience.
No
📌 Always:
> feat(elastic-search): improved default search

- docs/docs/guides/developer-guide/plugins/index.mdx
This PR clarifies the migration commands in the "Test the Plugin" section of the Vendure documentation. The current instructions are incomplete and could lead to confusion for users trying to test their plugins.
Changes:
**Updated the documentation to clearly separate the two steps required for migrations**:
- Generating the migration file using `npx vendure migrate wishlist-plugin`.
- Running the migration using `npx vendure migrate wishlist-plugin`.
**Why this matters:**
- The current documentation only mentions the first step (npm run migration:generate), which give error on cmd.
- By explicitly stating both steps, users can seamlessly test their plugins without confusion or errors.
No
📌 Always:
> docs: Clarify migration commands for testing plugins

- docs/docs/guides/developer-guide/plugins/index.mdx
Removed the unused `WishlistItem` import from the resolver code snippet in the documentation.  
- Removed `import { WishlistItem } from '../entities/wishlist-item.entity';` as it was unused in the snippet.  
Improves code quality and avoids confusion for developers following the documentation.  
The import was not used in the provided resolver snippet, and removing it ensures cleaner and more accurate examples.  
No
📌 Always:
> fix(docs): Remove unused import "WishlistItem" from resolver snippet

- docs/docs/guides/developer-guide/plugins/index.mdx
Removed the redundant word "in" at the beginning of the plugins introduction section in the docs.  
- Removed "in" from the first sentence of the plugins section.  
Improves readability and clarity of the documentation.  
The sentence flows better without the unnecessary word.  
No
📌 Always:
> fix(docs): Remove redundant "in" from plugins introduction

- packages/core/e2e/product.e2e-spec.ts
- packages/core/src/service/services/product-variant.service.ts
Avoids throwing an error checking for variant option combinations that already exist when updating variants.
Related Issue: #3190
no
Error doesnt show up now when updating an variant while also specifying the current optionIds
But is thrown when trying to specify already existing optionIds while creating a new variant
📌 Always:
> fix(core): Avoid variant options combination check on updateProductVariant mutation

- packages/core/src/api/config/configure-graphql-module.ts
- packages/core/src/api/config/graphql-custom-fields.ts
Previously, adjustDraftOrderLine and other admin mutation on order lines did not include non-public custom OrderLine fields. This fixes that. I think my issue is the same as issue #3342 and this should fix #3342.
I also filtered out internal fields, as custom fields simply marked internal were showing in the order line input for both admin and shop api.
No known breaking changes
📌 Always:
> Fix(core): Allow non-public customOrderLineFields in admin api

- packages/core/src/api/common/graphql-value-transformer.ts
This pull request addresses a bug where GraphQL types in the TypeTree were becoming undefined when using nested fragment spreads. The issue stemmed from the way fragment children were being merged within the `getTypeNodeByPath` function.  It was performing a shallow merge, failing to properly incorporate type information from nested fragments. Relates to #3337.
📌 Always:
- [x ] I have set a clear title
- [ x] My PR is small and contains a single feature
- [x ] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
> fix(core): Fix undefined type issue with nested fragment spreads

- packages/core/src/service/helpers/order-calculator/order-calculator.ts
This is just a tiny refactor, that removes some commented out code and cleans up the `applyOrderItemPromotions` function
None
-
📌 Always:
> refactor(core): cleanup order-calculator's applyOrderItemPromotions

- packages/core/src/service/services/product-option-group.service.ts
Hey sir, I just updated one line, this PR is related to <https://github.com/vendure-ecommerce/vendure/issues/3281>, I can retrieve the `ProductOptionGroup` which had been soft deleted.
I use `removeOptionGroupFromProduct` to remove an `optionGroup` from a product,all the `productVariants` have been `softDelete`.
But after this remove,I can still use`ProductOptionGroup` GraphQL API get the `optionGroup` which had been soft deleted .I checked the database and the column `deletedAt` has value.
N/A
Database:
GraphQL:
Before Updating:
After Updating:
📌 Always:
> fix(core): Retrieve the softDelete ProductOptionGroup

- e2e-common/e2e-initial-data.ts
- packages/core/e2e/active-order-strategy.e2e-spec.ts
- packages/core/e2e/draft-order.e2e-spec.ts
- packages/core/e2e/order-multi-vendor.e2e-spec.ts
- packages/core/e2e/order-multiple-shipping.e2e-spec.ts
- packages/core/e2e/order.e2e-spec.ts
- packages/core/e2e/shipping-method.e2e-spec.ts
- packages/core/e2e/shop-order.e2e-spec.ts
- packages/core/e2e/utils/test-order-utils.ts
- packages/core/src/data-import/providers/populator/populator.ts
- packages/core/src/data-import/types.ts
- packages/core/src/service/helpers/order-modifier/order-modifier.ts
When cancelling and order that has a shipping line with a tax rate, the order total after the cancellation would be negative the amount of tax on the shipping method. This fixes that, and changes some order e2e tests to use a shipping method with a tax rate.
No known breaking changes
📌 Always:
> fix(core): fix order cancellation when shipping has tax

- packages/admin-ui/src/lib/catalog/src/components/product-options-editor/product-options-editor.component.html
- packages/admin-ui/src/lib/core/src/shared/components/data-table-2/data-table2.component.html
- packages/admin-ui/src/lib/core/src/shared/components/data-table-2/data-table2.component.ts
This issue occurs only when there is an option group with more than 10 options AND ProductOption has Custom fields.
In such case there are two problems when trying to navigate through option pages / update options custom fields:
1. Per page selector doesn't work, thus it always stays at 10 items per page
2. When switching pages using page selector, custom fields on pages > 1 binds to options from first page, cause ngFor gets an index as a tracking value 
PR doesn't include any breaking changes
📌 Always:
> fix(admin-ui): Fix incorrect tracking id on ProductOption's / ProductOption list per page switch

- license/signatures/version1/cla.json
- packages/admin-ui/src/lib/catalog/src/catalog.module.ts
- packages/admin-ui/src/lib/core/src/common/component-registry-types.ts
Changed the location of the product variants tab to 'product-variant-list'. Fixed a TypeScript error in the admin-ui catalog module by adding a type assertion to the 'product-variant-list' location.
No breaking changes. This is a simple type assertion fix that doesn't affect functionality.
N/A - This is a code-level fix with no visual changes.
📌 Always:
> fix(admin-ui): Product variant list location

- packages/admin-ui/src/lib/core/src/shared/components/data-table-2/data-table2.component.ts
related issue: https://github.com/vendure-ecommerce/vendure/issues/3403
Pagination now appears as “0 - 10 of [total]” or “10 - 20 of [total]”. It is necessary to adjust the starting index by adding 1.
none
📌 Always:
> fix(admin-ui): Fix incorrect pagination range

- packages/job-queue-plugin/src/bullmq/bullmq-job-queue-strategy.ts
Fix ignoring values (like concurrency) from workerOptions other than removeOnComplete and removeOnFail
Resolves: #3425 
no
Not applicable
📌 Always:
> fix(job-queue-plugin): Fix ignoring values from workerOptions

- docs/docs/guides/developer-guide/worker-job-queue/index.mdx
Update documentation for RequestContext serialization to correctly use `ctx.serialize()` instead of `RequestContext.serialize(ctx)`. This change resolves an issue where the documentation incorrectly referenced a static method that does not exist, leading to confusion.
N/A
N/A
📌 Always:
> docs: fix incorrect RequestContext serialization method

- .gitignore
- packages/core/e2e/payment-method.e2e-spec.ts
- packages/core/e2e/shipping-method.e2e-spec.ts
- packages/core/src/api/api-internal-modules.ts
- packages/core/src/api/resolvers/shop/shop-payment-methods.resolver.ts
- packages/core/src/api/resolvers/shop/shop-shipping-methods.resolver.ts
- packages/core/src/api/schema/shop-api/shop.api.graphql
- packages/core/src/service/services/payment-method.service.ts
I propose adding two public GraphQL queries in the Vendure core:
```
1.	activePaymentMethods – Returns a list of all active PaymentMethods.
2.	activeShippingMethods – Returns a list of all active ShippingMethods.
```
These queries would allow frontend developers to dynamically fetch and display the current active methods without requiring access to the cart or checkout state. This would ensure consistency between the backend configuration and the frontend display, reducing the need for manual intervention when changes are made.
```graphQL
query activePaymentMethods {
activePaymentMethods {
id
name
code
description
translations {
id
languageCode
name
description
}
}
}
query activeShippingMethods {
activeShippingMethods {
id
name
code
description
translations {
id
languageCode
name …
```
> feat(core): Add two new queries (shop-api) to get public payment and shipping methods

- packages/elasticsearch-plugin/src/build-elastic-body.spec.ts
- packages/elasticsearch-plugin/src/build-elastic-body.ts
- packages/elasticsearch-plugin/src/elasticsearch.service.ts
- packages/elasticsearch-plugin/src/options.ts
Adds the request context to mapQuery, allowing searching to be based of the customer, such as filtering on whether the customer is in a group.
None
📌 Always:
> feat(elastic-search): add request context to mapQuery

- packages/dashboard/src/app/styles.css
- packages/dashboard/vite/vite-plugin-theme.ts
- packages/dashboard/vite/vite-plugin-vendure-dashboard.ts
Introduces the ability to theme the dashboard via the Vite plugin. Shadcn variables for both dark and light mode can be overridden. 
Custom variables can be also passed, they will also end up in the CSS variables.
> feat(dashboard): Introduce theme variables plugin for dynamic theming

- packages/admin-ui/src/lib/core/src/shared/components/modal-dialog/modal-dialog.component.scss
This PR adds support for dark mode in the modal component.  
It updates the modal styling to align with the dark theme and ensures proper contrast and readability across light and dark modes to solve the issue #3431 
No breaking changes.
**Light Mode:**
**Dark Mode:**
I have read the CLA Document and I hereby sign the CLA
> Modal Dark mode message readability improvement

- packages/email-plugin/src/generator/handlebars-mjml-generator.ts
The "formatMoney" helper should format the amount with the given locale, even without currencyCode being set.
> The Handlebars "formatMoney" helper should always return the correctly formatted amount

- packages/core/src/plugin/plugin-utils.ts
When using the compileUiExtensions, the proxy path was broken due to some breaking changes in proxy middleware, which ends up in an endless redirect loop.
https://github.com/chimurai/http-proxy-middleware/blob/master/MIGRATION.md#removed-requrl-patching
No
📌 Always:
- [z] I have set a clear title
- [z] My PR is small and contains a single feature
> feat(admin-ui-plugin): support proxy-middleware v2 to v3

- docs/docs/guides/developer-guide/custom-fields/index.md
- docs/docs/guides/developer-guide/plugins/index.mdx
Personally was looking for custom field docs for custom entities but couldnt find them both in the plugin, nor on custom fields sections. They're located in ["Define a database entity"](https://docs.vendure.io/guides/developer-guide/database-entity/#supporting-custom-fields), so I thought let's link to there to save someone else's time.
---
Another note: Running `npm run docs:build` resulted in many many markdown file whitespace changes, which I now purposefully didnt include in the patch. Is that only happening for me, some local linter thingy? Would be cool to harden this but I'm not sure what causes this just wanted to take note.
None.
| Header | Header |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/e97acd9a-86d0-4bc9-b7f5-bb8f5f5a7f2f) | …
> docs(core): Add notes about custom fields on custom entities

- packages/admin-ui-plugin/src/plugin.ts
- packages/email-plugin/src/dev-mailbox.ts
Some paths in sendFile causes a notFound error in [Send](https://github.com/pillarjs/send/blob/fb1bed76209e88f3b83f0b52dc5f9783e820aaaf/index.js#L451) used by Express By setting the root as an option we can ensure it works while using pnpm.
- 
📌 Always:
> feat(admin-ui-plugin): fixed an issue with sendFile and absolute paths

- packages/core/src/plugin/default-job-queue-plugin/clean-jobs-task.ts
Use the `job` alias for the query builder. 
See https://discord.com/channels/1100672177260478564/1371844277881147452
Nope
📌 Always:
> fix(job-queue): use job alias for clean-jobs task

- packages/payments-plugin/e2e/mollie-payment.e2e-spec.ts
- packages/payments-plugin/src/mollie/mollie.service.ts
The Mollie Plugin is checking for allowed payment methods, but `klarna` is not allowed. **This is because the plugin uses an outdated version of Mollie NodeJS package.**
This PR removes the check in Vendure, and lets the Mollie API handle the error when an invalid payment method code is passed.
:warning: 
> Why not update the Mollie Node package?
I have attempted to upgrade the Mollie Node package, but that resulted in some bugs. These have been reported at Mollie and fixed, but upgrading the node package is not a small task. I would like to make that big change together with #2921to prevent duplicate work. 
However, we would like to have this fix before that time, because we now can not have payment method selection in our  own storefront, and are stuck with the Mollie hosted checkout. …
> feat(payments-plugin): Unable to use `klarna` payment via Mollie

- docs/docs/guides/developer-guide/scheduled-tasks/index.md
Fixed a type mismatch between the actual execute definition and the code sample in the documentation. The execute function in scheduled tasks should use object destructuring to access the injector and params, rather than receiving them as separate parameters.
Changed from:
```typescript
async execute(injector, params) {
```
To:
```typescript
async execute({injector, params}) {
```
This change aligns with the TypeScript interface definition in `@vendure/core/dist/scheduler/scheduled-task.d.ts` which defines the execute method as:
```typescript
execute(args: ScheduledTaskExecutionArgs<C>): Promise<any>;
```
Where `ScheduledTaskExecutionArgs` is an object containing `injector`, `scheduledContext`, and `params`.
No breaking changes. This is a type-level fix that ensures the code matches the …
> Fix: Correct execute function signature in purchase-group-tasks

- packages/core/e2e/custom-field-relations.e2e-spec.ts
- packages/testing/src/data-population/populate-for-testing.ts
why are the Node 20 sql.js e2e tests failing? Adding some logging to diagnose.
> chore: Add logging to e2e test to diagnose e2e test failure

- packages/core/src/service/helpers/entity-hydrator/merge-deep.spec.ts
- packages/core/src/service/helpers/entity-hydrator/merge-deep.ts
closes #3355 by tracking visited objects in a `WeakSet` and skipping the merge process if we encounter them again. This seems to prevent `RangeError: Maximum call stack size exceeded` when there's a cyclic reference.
No
📌 Always:
> fix: circular merge-deep issue

- docs/docs/guides/getting-started/graphql-intro/index.mdx
- docs/docs/guides/getting-started/try-the-api/index.mdx
- docs/src/components/Playground/index.tsx
- docs/src/pages/index.tsx
This updates the custom playground component in the Docusaurus docs to use the new API provided by
the GraphiqlPlugin.
Note: this should not be merged until the Vendure demo instance has been update to v3.3.1+
Closes #3496
> Use GraphiQL in the Vendure docs

- packages/core/src/api/config/get-final-vendure-schema.ts
- packages/core/src/plugin/vendure-plugin.ts
See https://github.com/vendure-ecommerce/vendure/issues/3165
As JavaScript behaves this way, no breaking changes should be included:
📌 Always:
> Pass schema into api extension definition

- packages/core/src/api/resolvers/entity/product-option-entity.resolver.ts
- packages/core/src/api/resolvers/entity/product-option-group-entity.resolver.ts
- packages/core/src/service/services/product-option-group.service.ts
- packages/core/src/service/services/product-option.service.ts
Fixes #3502 
- Allows fetching of deleted option group when connected to a product option (i.e. in old orders)
- Filters out soft deleted option groups from productOptionGroups query.
- Filters out soft deleted option groups from product.optionGroups field resolver.
- Filters out soft deleted options on their findAll and findOne method.
Previous attempt #3503 
None
📌 Always:
> fix(core): Improve ProductOptionGroup soft-delete handling

- packages/core/e2e/shipping-method.e2e-spec.ts
- packages/core/src/config/shipping-method/default-shipping-calculator.ts
The tax rate should be of type floating-point, as some countries (e. g. Switzerland) do have a fractional part in their VAT.
> Assign type 'float' to taxRate of defaultShippingCalculator

- docs/docs/guides/developer-guide/custom-fields/index.md
- packages/core/src/api/config/__snapshots__/graphql-custom-fields.spec.ts.snap
- packages/core/src/api/config/graphql-custom-fields.spec.ts
- packages/core/src/api/config/graphql-custom-fields.ts
- packages/core/src/api/resolvers/admin/global-settings.resolver.ts
- packages/core/src/api/schema/common/custom-field-types.graphql
- packages/core/src/config/custom-field/custom-field-types.ts
This PR adds support for marking custom fields as deprecated using the `@deprecated` GraphQL directive. This feature enables smooth API evolution by allowing developers to mark fields for future removal while providing clear migration guidance.
- **TypeScript Types**: Added `deprecated?: boolean | string` property to custom field configuration
- **GraphQL Schema**: Added deprecation fields to CustomField interface and all implementations
- **Schema Generation**: Custom fields marked as deprecated now generate `@deprecated` directives in the GraphQL schema
- **Resolver Updates**: Global settings resolver now handles deprecation metadata
- **Tests**: Added comprehensive test coverage for deprecation functionality
```typescript
{
name: 'oldField',
type: 'string',
deprecated: true
}
``` …
> feat(core): Add support for deprecating custom fields with @deprecated directive

- packages/dashboard/src/lib/framework/layout-engine/location-wrapper.tsx
The rings in hover mode were touching the text of the elements and it looked very unpolished. 
after:
before: 
📌 Always:
> fix(dashboard): Add "ring offeset" padding on devmode on hover ring
