packages/core/src/bootstrap.ts, packages/dev-server/index-worker.ts
=> fix(race-condition): Fix race condition on DB among worker and server

packages/admin-ui/src/app/catalog/components/product-detail/product-detail.component.ts
Hello @michaelbromley , this fixes an error that appears when you land on `product detail` admin page
=> fix(admin-ui): Fix customField product error: handle undef. case

packages/admin-ui/src/app/order/components/fulfillment-detail/fulfillment-detail.component.ts, packages/admin-ui/src/app/order/components/line-fulfillment/line-fulfillment.component.ts, packages/admin-ui/src/app/order/components/order-history/order-history.component.ts
=> fix(admin-ui): Correct types for OrderDetail

docs/content/docs/plugins/extending-the-admin-ui/using-other-frameworks/_index.md
It's literally just one letter
=> fix(doc) Fix small import typo

.github/workflows/build_and_test.yml
Attempting to fix the "reference is not a tree" error that has started occurring.
=> chore: Log disk usage in CI for e2e step

packages/core/src/i18n/messages/en.json, packages/core/src/service/helpers/order-calculator/order-calculator.ts
- Throw error when no active tax zone is not found in channel
=> chore: Throw error when no active tax zone in channel

packages/core/src/i18n/messages/en.json
- chore: Add missing message translation
=> chore: Add missing message translation

docs/content/docs/plugins/extending-the-admin-ui/_index.md
Fix for docs and example code for build ui extensions for admin UI as deployment step.
=> feat(docs): Fix example code for admin ui build as deployment step

packages/elasticsearch-plugin/src/build-elastic-body.ts, packages/elasticsearch-plugin/src/options.ts
The discussion for the feature took place in #364.
=> feat(elasticsearch-plugin): Added mapQuery option

docs/content/docs/developer-guide/updating-vendure.md
=> Update updating-vendure.md (Fix broken link)

docs/content/docs/developer-guide/customizing-models.md
Just fix the indentation on code example.
=> fix(doc): Indentation on Customizing Models

packages/admin-ui/i18n-coverage.json, packages/admin-ui/src/lib/core/src/shared/pipes/state-i18n-token.pipe.ts, packages/admin-ui/src/lib/static/i18n-messages/cs.json, packages/admin-ui/src/lib/static/i18n-messages/de.json, packages/admin-ui/src/lib/static/i18n-messages/en.json, packages/admin-ui/src/lib/static/i18n-messages/es.json, packages/admin-ui/src/lib/static/i18n-messages/pl.json, packages/admin-ui/src/lib/static/i18n-messages/pt_BR.json, packages/admin-ui/src/lib/static/i18n-messages/zh_Hans.json, packages/admin-ui/src/lib/static/i18n-messages/zh_Hant.json
-add missing "state.error" token (one of the Payment states)
=> fix: Add missing "state.error" token

README.md
=> Updated server start command documentation

packages/admin-ui/src/lib/core/src/shared/components/channel-assignment-control/channel-assignment-control.component.html, packages/admin-ui/src/lib/core/src/shared/components/channel-assignment-control/channel-assignment-control.component.ts, packages/admin-ui/src/lib/settings/src/components/role-detail/role-detail.component.ts
Hey,
I was using the channel-assignment-control.component when i noticed that the channel values were not correctly displayed.
You can check the bug when editing a role with channels.
=> fix(admin-ui): Channel value display

packages/core/src/config/custom-field/custom-field-types.ts, packages/core/src/config/default-config.ts, packages/core/src/entity/channel/channel.entity.ts, packages/core/src/entity/custom-entity-fields.ts, packages/core/src/entity/register-custom-entity-fields.ts
=> feat(core): Support custom fields on Channel entity

docs/content/docs/plugins/writing-a-vendure-plugin.md
Added hint for `CustomFields` configuration in [Writing A Vendure Plugin](https://www.vendure.io/docs/plugins/writing-a-vendure-plugin/) Docs referencing  [Customizing Models With Custom Fields](https://www.vendure.io/docs/developer-guide/customizing-models/)
=> Added hint for `CustomFields` configuration in `Writing A Vendure Plugin` docs

packages/admin-ui/src/lib/static/i18n-messages/pt_BR.json
Ready to integrate, just a small typing error, i have noticed.
=> fix(admin-ui): Typing error on pt-Br i18n

packages/core/src/service/services/payment-method.service.ts
=> fix(core): Made addPaymentToOrder channel aware

packages/core/src/event-bus/events/customer-address-event.ts, packages/core/src/event-bus/events/customer-event.ts, packages/core/src/event-bus/index.ts, packages/core/src/service/services/customer.service.ts
The ability to subscribe to Customer events and Address events
=> feat(core): Add CustomerEvent and CustomerAddressEvent

packages/core/src/service/services/collection.service.ts
When recalculating all Collections, this query would consume a lot of memory. Instead of querying all Collections before the loop, the Collections are queried individually inside the loop.
=> perf(core): reduce memory usage of apply-collection-filters job

docs/content/docs/developer-guide/customizing-the-order-process/index.md
docs: Added hint for multiple custom states
=> Added hint for multiple custom states

packages/admin-ui/src/lib/marketing/src/components/promotion-list/promotion-list.component.html, packages/admin-ui/src/lib/marketing/src/components/promotion-list/promotion-list.component.scss, packages/admin-ui/src/lib/marketing/src/components/promotion-list/promotion-list.component.ts, packages/admin-ui/src/lib/static/i18n-messages/cs.json, packages/admin-ui/src/lib/static/i18n-messages/de.json, packages/admin-ui/src/lib/static/i18n-messages/en.json, packages/admin-ui/src/lib/static/i18n-messages/es.json, packages/admin-ui/src/lib/static/i18n-messages/fr.json, packages/admin-ui/src/lib/static/i18n-messages/pl.json, packages/admin-ui/src/lib/static/i18n-messages/pt_BR.json, packages/admin-ui/src/lib/static/i18n-messages/ru.json, packages/admin-ui/src/lib/static/i18n-messages/zh_Hans.json, packages/admin-ui/src/lib/static/i18n-messages/zh_Hant.json
Changes in this pull request will allow users to filter promotions by name or coupon code.
=> feat(admin-ui): Add ability to filter promotions by name or coupon code

packages/core/src/service/services/customer.service.ts
=> fix(core): Make verifyCustomerAccount channel independent

packages/elasticsearch-plugin/docker-compose.yml, packages/elasticsearch-plugin/src/build-elastic-body.spec.ts, packages/elasticsearch-plugin/src/build-elastic-body.ts, packages/elasticsearch-plugin/src/elasticsearch.service.ts, packages/elasticsearch-plugin/src/options.ts, packages/elasticsearch-plugin/src/types.ts
Close #976
Moreover, update elastic version in docker-compose.yml
=> fix(elastic): add totalItemsMaxSize option

packages/elasticsearch-plugin/package.json, packages/elasticsearch-plugin/src/elasticsearch-index.service.ts, packages/elasticsearch-plugin/src/elasticsearch-resolver.ts, packages/elasticsearch-plugin/src/elasticsearch.service.ts, packages/elasticsearch-plugin/src/indexer.controller.ts, packages/elasticsearch-plugin/src/indexing-utils.ts, packages/elasticsearch-plugin/src/options.ts, packages/elasticsearch-plugin/src/plugin.ts, packages/elasticsearch-plugin/src/types.ts, yarn.lock
=> feat(elastic): add ability to customize index options and mappings

packages/elasticsearch-plugin/e2e/elasticsearch-plugin.e2e-spec.ts, packages/elasticsearch-plugin/src/build-elastic-body.spec.ts, packages/elasticsearch-plugin/src/build-elastic-body.ts, packages/elasticsearch-plugin/src/constants.ts, packages/elasticsearch-plugin/src/elasticsearch.service.ts, packages/elasticsearch-plugin/src/indexer.controller.ts, packages/elasticsearch-plugin/src/indexing-utils.ts, packages/elasticsearch-plugin/src/types.ts
Close #1018 
Close #1017  
@michaelbromley how can i pack new version of package and push it to npm to test on dev?
=> bugfix(elastic-search-plugin): use only one index in elastic-search-plugin

packages/elasticsearch-plugin/src/elasticsearch.service.ts
Fix bug that was introduced in #1086
=> fix(elastic-search-plugin): fix bug with facetValueMaxSize #1018

packages/core/src/service/services/product-variant.service.ts
=> fix(core):  Fixed wrong event type when a variant is created

docs/content/developer-guide/importing-product-data.md
Added examples of payment method and roles definition. Based on the [issue](https://github.com/vendure-ecommerce/vendure/issues/1202).
=> docs(Developer Guide, Importing Product Data): Added example of payment method and roles definition

packages/elasticsearch-plugin/e2e/elasticsearch-plugin.e2e-spec.ts, packages/elasticsearch-plugin/src/api/api-extensions.ts, packages/elasticsearch-plugin/src/options.ts, packages/elasticsearch-plugin/src/types.ts
Added option to hide indexed fields in api #1181
I hope it's okay to already push it to minor branch.
=> feat(elasticsearch-plugin): Added option to hide indexed fields in api

packages/core/src/service/services/product.service.ts
Closes #1234. I've also fixed a typo in the description comment.
=> fix(core): Fix ProductService.assignProductsToChannel to properly assign assets to channel

packages/admin-ui/src/lib/static/styles/global/_utilities.scss
=> fix(admin-ui): Issue #1293, corrects the warning about the division in Sass

packages/core/src/service/services/customer.service.ts
=> Fixed verification

docs/content/developer-guide/payment-integrations/index.md
=> Fix payments-plugin link in developer guide

packages/core/src/service/services/channel.service.ts, packages/core/src/service/services/zone.service.ts
Currently there is no way to mock caches on `ChannelService` and `ZoneService`.
This pull requests adds `createCache()` function to allow developers override and mock it if needed.
Also `initZones()` and `initChannels()` now ensures that cache exists, and do not recreate it on each call.
=> refactor(core): Allow to mock self-refreshing cache for channels and zones

packages/core/src/api/resolvers/entity/order-line-entity.resolver.ts, packages/core/src/service/services/order.service.ts
=> fix(OrderLineEntityResolver): Add missing Order resolveField

packages/payments-plugin/src/stripe/stripe.controller.ts
Fix state transitioning for orders that are already in 'ArrangingPayment' state for stripe payment_intent webhook endpoint.
This happens when using vue-storefront/vendure when adding a billing address ([see updateAddressDetails/index.ts](https://github.com/vuestorefront-community/vendure/blob/15b03f4da3398a968e7bd64976b8bf9958456c64/packages/api-client/src/api/updateAddressDetails/index.ts#L26))
Same implementation as for mollie payment service ([mollie.service.ts](https://github.com/vendure-ecommerce/vendure/blob/c6cf4d4e214f3941bc5f27017b0354dda732f9e0/packages/payments-plugin/src/mollie/mollie.service.ts#L138))
=> fix(payment-plugin,stripe): fix state transitioning 

packages/payments-plugin/src/stripe/stripe.controller.ts
Fix: added a return(202) to stripe webhook in case of successfull payment
=> Fix: added a return(202) to stripe webhook in case of successfull payment

packages/ui-devkit/src/compiler/compile.ts
To allow spaces in output path.
=> fix(ui-devkit): Wrap output path in quotes.

packages/admin-ui/src/lib/dashboard/src/components/dashboard-widget/dashboard-widget.component.ts
=> fix(admin-ui): Fix dashboard widget change detection logic

docs/content/developer-guide/deployment.md
Fix link to introspection in [documentation](https://www.vendure.io/docs/developer-guide/deployment/#security-considerations).
=> fix(docs): Fix introspection link

docs/content/developer-guide/deployment.md, packages/admin-ui/src/lib/core/src/shared/components/data-table/data-table.component.html, packages/admin-ui/src/lib/core/src/shared/components/data-table/data-table.component.ts, packages/admin-ui/src/lib/static/i18n-messages/cs.json, packages/admin-ui/src/lib/static/i18n-messages/de.json, packages/admin-ui/src/lib/static/i18n-messages/en.json, packages/admin-ui/src/lib/static/i18n-messages/es.json, packages/admin-ui/src/lib/static/i18n-messages/fr.json, packages/admin-ui/src/lib/static/i18n-messages/it.json, packages/admin-ui/src/lib/static/i18n-messages/pl.json, packages/admin-ui/src/lib/static/i18n-messages/pt_BR.json, packages/admin-ui/src/lib/static/i18n-messages/pt_PT.json, packages/admin-ui/src/lib/static/i18n-messages/ru.json, packages/admin-ui/src/lib/static/i18n-messages/uk.json, packages/admin-ui/src/lib/static/i18n-messages/zh_Hans.json, packages/admin-ui/src/lib/static/i18n-messages/zh_Hant.json
Show current start,end and total items in datatable:
Not too comfortable with Angular, so let me know if this is the desired approach.
=> Feat(admin-ui): show total items in datatables

packages/elasticsearch-plugin/src/plugin.ts
https://github.com/vendure-ecommerce/vendure/issues/1598
=> fix(elasticsearch-plugin): Missing CustomMappingsResolver in Admin-api

packages/core/src/job-queue/subscribable-job.ts
Introduced errorOnFail flag to control this behavior. Fixes #1551
=> fix(core): Controllable fail of job.updates() observable sequence (#1551)

docs/content/developer-guide/deployment.md
=> Little typo in deployment docs.

packages/core/src/event-bus/events/initializer-event.ts, packages/core/src/event-bus/index.ts, packages/core/src/service/initializer.service.ts
Added event for a finished initialization (#1618)
=> feat(event): Added event for a finished initialization (#1618)

packages/asset-server-plugin/src/common.ts
https://github.com/vendure-ecommerce/vendure/issues/1640
=> fix(asset-server-plugin): fix asset url behind a proxy

packages/core/e2e/shop-order.e2e-spec.ts, packages/core/src/service/helpers/order-modifier/order-modifier.ts, packages/core/src/service/services/order.service.ts
Fixes issue #1683 
I eagerly loaded OrderLine customFields in certain places.
Changed OrderLine customField equality function
Added tests
I was finding a lot of edge cases when I was programming this. This might not fix all of them.
=> Fix orderline customfield relations

packages/core/src/config/promotion/actions/order-fixed-discount-action.ts, packages/dev-server/dev-config.ts
Prevent negative order total when using fixed discounts. Resolve #1717
=> fix(core): Prevent negative order total with fixed discounts

packages/core/src/api/common/custom-field-relation-resolver.service.ts, packages/core/src/common/configurable-operation.ts, packages/core/src/service/helpers/entity-hydrator/entity-hydrator.service.ts, packages/core/src/service/helpers/locale-string-hydrator/locale-string-hydrator.ts, packages/core/src/service/helpers/order-modifier/order-modifier.ts, packages/core/src/service/helpers/translator/translator.service.ts, packages/core/src/service/helpers/translator/translator.ts, packages/core/src/service/helpers/utils/translate-entity.spec.ts, packages/core/src/service/helpers/utils/translate-entity.ts, packages/core/src/service/service.module.ts, packages/core/src/service/services/collection.service.ts, packages/core/src/service/services/country.service.ts, packages/core/src/service/services/customer.service.ts, packages/core/src/service/services/facet-value.service.ts, packages/core/src/service/services/facet.service.ts, packages/core/src/service/services/order-testing.service.ts, packages/core/src/service/services/order.service.ts, packages/core/src/service/services/product-option-group.service.ts, packages/core/src/service/services/product-option.service.ts, packages/core/src/service/services/product-variant.service.ts, packages/core/src/service/services/product.service.ts, packages/core/src/service/services/shipping-method.service.ts, packages/core/src/service/services/zone.service.ts
=> fix(core): Translation don't use DefaultLanguage of Channel (#1730)

packages/core/src/service/services/order.service.ts
=> fix(core): delete order method

packages/core/src/service/services/promotion.service.ts
=> fix(core): persist customField relations in PromotionService

packages/elasticsearch-plugin/src/indexing/indexer.controller.ts
**Reduces the size of the object when deleting products in the index**
See issue #1837 for more context
This PR reduces the size of the product object 
Before
```
{
createdAt: 2022-09-08T16:37:50.105Z,
updatedAt: 2022-09-15T05:20:53.622Z,
deletedAt: null,
enabled: true,
id: '5f111d8a-e1f5-4c65-a461-a822eea9fc42',
customFields: CustomProductFields {
... a lot of custom fields here
},
translations: [
ProductTranslation {
createdAt: 2022-09-08T16:37:50.060Z,
updatedAt: 2022-09-08T16:37:50.105Z,
languageCode: 'fr',
name: 'ChaussExpo',
slug: 'chaussexpo',
description: '',
id: '8d66d250-128e-4413-b923-66d416725931'
}
],
variants: [
ProductVariant {
createdAt: 2022-09-08T16:37:51.170Z,
updatedAt: 2022-09-15T05:20:53.237Z,
deletedAt: null,
enabled: true,
sku: 'CCCHAUSSEXRJALGEBR',
stockOnHand: …
```
=> fix(elasticsearch-plugin): Delete product - reduce object memory size

docs/content/developer-guide/authentication.md
=> docs: Update authentication.md

packages/admin-ui/src/lib/customer/src/components/customer-detail/customer-detail.component.ts, packages/admin-ui/src/lib/customer/src/providers/routing/customer-resolver.ts
Sort orders on customer details page by orderPlacedAt: 
- Resolve #1827
=> feat(admin): sort orders on customer details page

packages/core/src/api/middleware/auth-guard.ts
Add Subscription to parent type resolver action
fix problem when trying to authenticate a graphql subscription
replaces https://github.com/vendure-ecommerce/vendure/pull/1387
=> Fix: add Subscription to parentType

packages/admin-ui/src/lib/login/src/components/login/login.component.html, packages/admin-ui/src/lib/login/src/components/login/login.component.scss, packages/admin-ui/src/lib/login/src/components/login/login.component.ts
This PR adds some necessary links to Unsplash in the login image component
=> fix(admin-ui): Add links according to Unsplash guidelines

docs/content/plugins/writing-a-vendure-plugin.md
Btw: Something else that might be helpful in this page is something about where in the file structure to put the files.
=> fix: correct typo in writing-a-vendure-plugin.md

docs/content/developer-guide/customizing-the-order-process/index.md
Just something that caught my eye when reading the docs!
=> fix(docs): fix typos

packages/asset-server-plugin/src/constants.ts, packages/asset-server-plugin/src/plugin.ts, packages/asset-server-plugin/src/types.ts
Added a configurable Cache-Control header to asset response #1997
=> Added a configurable Cache-Control header

packages/core/src/service/services/product-variant.service.ts
=> fix(core): Filter out deleted options groups

packages/testing/src/test-server.ts
has testing in my local `esm` project.
=> feat(test): Add tokenMethod cookie support for TestServer

packages/dev-server/dev-config.ts, yarn.lock
replace hard-coded values with env variables for getDbConfig
=> fix(dev-server): Use env variables for db config

packages/core/e2e/fast-importer.e2e-spec.ts, packages/core/src/data-import/providers/importer/fast-importer.service.ts, packages/dev-server/.gitignore, packages/dev-server/dev-config.ts
implements slug normalization and related test
fixes #2053
adds fallback values to dbConfig for dev-server to run scripts from cli
=> fix(core): Slugify product created with fast importer service

packages/asset-server-plugin/src/plugin.ts
=> fix(asset-server-plugin): Change image format with no other transforms

packages/admin-ui/package-lock.json, packages/admin-ui/src/lib/settings/src/components/administrator-list/administrator-list.component.html, packages/admin-ui/src/lib/settings/src/components/administrator-list/administrator-list.component.scss, packages/admin-ui/src/lib/settings/src/components/administrator-list/administrator-list.component.ts, packages/admin-ui/src/lib/static/i18n-messages/cs.json, packages/admin-ui/src/lib/static/i18n-messages/de.json, packages/admin-ui/src/lib/static/i18n-messages/en.json, packages/admin-ui/src/lib/static/i18n-messages/es.json, packages/admin-ui/src/lib/static/i18n-messages/fr.json, packages/admin-ui/src/lib/static/i18n-messages/it.json, packages/admin-ui/src/lib/static/i18n-messages/pl.json, packages/admin-ui/src/lib/static/i18n-messages/pt_BR.json, packages/admin-ui/src/lib/static/i18n-messages/pt_PT.json, packages/admin-ui/src/lib/static/i18n-messages/ru.json, packages/admin-ui/src/lib/static/i18n-messages/uk.json, packages/admin-ui/src/lib/static/i18n-messages/zh_Hans.json, packages/admin-ui/src/lib/static/i18n-messages/zh_Hant.json
search field added on administrators list for followeing fields.
- First name
- Last name
- Email
=> search field added on administrators list on dashboard -> administrator.

packages/dev-server/test-plugins/multivendor-plugin/service/mv.service.ts
Refer: https://github.com/vendure-ecommerce/vendure/discussions/2156#discussioncomment-5778063
=> fix(dev-server): Update multivendor plugin property 'currencyCode'

packages/payments-plugin/src/mollie/mollie.service.ts, yarn.lock
* Removed error logging when Mollie sends a webhook with status `expired`, because this is not considered an error. It's fine if a Mollie session expires and a user tries to pay again later.
* Some linting fixes that occurred when trying to commit
=> fix(payments-plugin): Removed invalid error logging

packages/admin-ui/src/lib/customer/src/customer.routes.ts
the customer breadcrumb was going to itself, changed.
=> change breadcrumb for customers

packages/admin-ui/src/lib/settings/src/components/channel-detail/channel-detail.component.ts
This commit introduces a change to the `generateToken` method, improving the security of the token generation process. The previous implementation relied on `Math.random()`, which is not ideal for cryptographic purposes. The updated implementation now utilizes the `crypto.getRandomValues` function to generate an array of random bytes. These bytes are then converted into a standardized hexadecimal string representation, resulting in more secure and reliable tokens.
=> refactor: update generateToken method to use secure random number generation

packages/admin-ui/src/lib/core/src/data/providers/interceptor.ts
This PR closes #2136.
We are currently facing an issue with the AdminUI. 
Indeed, we configure a `loginUrl` towards a custom page which is internal (it shares the same origin as the rest of the AdminUI pages).
Therefore, when admins click on a link and face a `FORBIDDEN` error, they used to be totally redirected towards this `loginUrl` with a `window.location.href = loginUrl`, without the `?redirectTo` query parameter.
In this PR, I made sure to check if the `loginUrl` is on the same origin than the AdminUI (`window.location.origin`). If that is the case, we redirect to that internal `loginUrl` and provide the `?redirectTo` query parameter.
1. In the `vendure-ui-config.json` file, add the following to define a custom `loginUrl`:
```json
"loginUrl": "http://localhost:4200/admin/login",
``` …
=> feat(admin-ui): Redirect to the right page on forbidden errors if an internal `loginUrl` is provided

packages/admin-ui/src/lib/order/src/components/order-table/order-table.component.html
Fix quantity label in order table. 🙂
=> fix(admin-ui): Fix quantity label in order table

packages/core/src/entity/surcharge/surcharge.entity.ts
This fixes https://github.com/vendure-ecommerce/vendure/issues/2293
=> fix(core): Use MoneyStrategy in Surcharges

docs/content/plugins/extending-the-admin-ui/_index.md
Added a few tips to Extending the Admin UI page based on recent challenges with the output dist file.
=> Added tips to "Extending the Admin UI" page.

packages/core/src/common/index.ts, packages/core/src/entity/index.ts
Adding some export into core module, for example, the seller entity and calculated decorator. This improvement is for create plugins with this entity and decorator with more clean code.
Best.
Carlo.
=> Refactor core entity index and common index

packages/core/src/service/services/promotion.service.ts
closes https://github.com/vendure-ecommerce/vendure/issues/2375
=> fix: fix promotion channel association on update

docs/docs/guides/extending-the-admin-ui/getting-started/index.md
This pr fixes yarn add command typo for dev dependencies.
=> docs(common): Fix yarn add command

docs/docs/guides/developer-guide/overview/index.md
Sorry to make these one by one -- I haven't set up a local dev repo yet, but I wanted to surface these minor typos I found in the docs while they are fresh in my mind.
=> Add missing words (benefits from) in tech stack description

docs/docs/guides/storefront/connect-api/index.mdx
Under successful conditions `errors` is undefined - Meaning you'd never go down this branch and persist your token like you'd actually want. :smile: 
Btw - on another note: I had to manually search for the file because the "Edit this page" buttons dont work - those point to the wrong branch "new-docs"
=> Fix tanstack responseMiddleware

docs/docs/reference/admin-ui-api/react-hooks/use-lazy-query.md, packages/admin-ui/src/lib/react/src/react-hooks/use-query.ts
The aim is to be able to execute a graphql query in response to an event (a click on a button for example). In the same way as we do with useMutation. Today, the useQuery is executed as soon as the React component is loaded, which limits its use.
A complete example of use is available in the code.
More info about useLazyQuery in [Apollo documentation](https://www.apollographql.com/docs/react/api/react/hooks/#uselazyquery)
No breaking changes
In dev-server/ui-extensions-library/ui/react-components/ReactUI.tsx
Add
```
import {useLazyQuery} from '@vendure/admin-ui/react';
const GET_PRODUCT = gql`
query GetProduct($id: ID!) {
product(id: $id) {
id
name
description
}
}`;
type ProductResponse = {
product: {
name: string
description: string
}
}
export function ReactUi() {
const [getProduct, { …
```
=> feat(admin-ui): Add React useLazyQuery hook

packages/admin-ui/src/lib/catalog/src/components/create-product-variant-dialog/create-product-variant-dialog.component.ts
=> fix(admin-ui): Fix getting currencyCode in create product variant dialog

docs/docs/guides/core-concepts/promotions/index.md
=> fix(docs): Correct  `free-gift-action` example

docs/docs/reference/core-plugins/email-plugin/index.md, packages/email-plugin/src/handlebars-mjml-generator.ts, packages/email-plugin/src/plugin.spec.ts, packages/email-plugin/templates/order-confirmation/body.hbs, packages/email-plugin/test-templates/test-helpers/body.hbs
Added 2 new parameters to the `formatMoney` helper: currency and locale
Closes #2530
No
=> feat(email-plugin): Allow currencies with formatMoney helper

packages/email-plugin/templates/order-confirmation/body.hbs
=> fix(email-plugin): Remove Unwanted currency symbols

packages/admin-ui/src/lib/core/src/shared/components/ui-extension-point/ui-extension-point.component.ts
This PR fixes some syntax errors in the admin-ui code templates. (See https://github.com/vendure-ecommerce/vendure/issues/2544)
=> fix(admin-ui): Admin ui code templates

.github/workflows/build_and_test.yml, .github/workflows/publish_and_install.yml, CHANGELOG.md, packages/core/src/data-import/providers/populator/populator.ts, packages/core/src/data-import/types.ts
- Added missing field inheritFilters for Collection for InitialData. 
- Issue #2484 
No
=> Feat: #2484 (Add Missing inherit filters field)

packages/elasticsearch-plugin/src/indexing/indexer.controller.ts, packages/elasticsearch-plugin/src/options.ts
Given custom mapping access to the ctx, so they can add channel specific data
No
N/A
=> feat(elasticsearch-plugin): provide the ctx for custom mappings

packages/job-queue-plugin/src/pub-sub/pub-sub-job-queue-strategy.ts
Catching invalid messages
Better logging about message handling
No
=> feat(job-queue-plugin): Improve pub/sub message handling

packages/admin-ui/src/lib/static/i18n-messages/pt_BR.json
Fix for issue #2609 
Replaced wrong name for Vendure correct one
N/A
📌 Always:
- [N/A] I have added or updated test cases
- [N/A] I have updated the README if needed
=> fix: fixing pt_br translation #2609

docs/docs/guides/developer-guide/the-service-layer/index.mdx
Minor changes to improve clarity.
📌 Always:
=> docs: improve clarity

packages/admin-ui/README.md
The documentation for how to actually add a language to the Admin UI is a bit fragmented.
I propose we add this paragraph to make it clear how to actually integrate a new localisation and test it locally before pushing it to master.
No
📌 Always:
=> docs(admin-ui): How to verify localisation changes

packages/admin-ui/src/lib/static/i18n-messages/pt_BR.json
Fix for issue #2626
Replaced wrong name for Vendure correct one
N/A
📌 Always:
- [N/A] I have added or updated test cases
- [N/A] I have updated the README if needed
=> fix: fixing pt_br translation for #2626

docs/docs/reference/core-plugins/stellate-plugin/index.md
=> docs: correct property in Stellate configuration example

packages/core/src/config/custom-field/custom-field-types.ts, packages/core/src/config/default-config.ts, packages/core/src/entity/custom-entity-fields.ts, packages/core/src/entity/product-variant/product-variant-price.entity.ts
Support for custom fields on ProductVariantPrice.
No
📌 Always:
=> feat(core): Custom fields on ProductVariantPrice

packages/core/src/config/index.ts
OrderByCodeAccessStrategy and DefaultOrderByCodeAccessStrategy werer not exported, #2664
=> Export OrderByCodeAccessStrategy and DefaultOrderByCodeAccessStrategy

docs/docs/guides/developer-guide/migrations/index.md
Link head double '/' in the end, was giving a 404.
📌 Always:
- [x ] I have set a clear title
- [x ] My PR is small and contains a single feature
- [x ] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")
- [ x] I have updated the README if needed
=> Update index.md Fix Broken Link

docs/docs/guides/developer-guide/plugins/index.mdx
This PR corrects minor typos in the "Writing Your First Plugin" tutorial.
Does this PR include any breaking changes we should be aware of? No
📌 Always:
=> docs(plugin-tutorial): Fix typos on file and directory names

packages/core/src/job-queue/job-queue.ts
Implementation of: https://github.com/vendure-ecommerce/vendure/issues/2755
📌 Always:
=> feat(job-queue): dont swallow add errors

packages/core/src/job-queue/job-queue.ts
Added a missing parameter to call the Job strategy function
no
=> fix(core): Add missing jobOptions to a strategy `jobQueueStrategy.add` function

packages/admin-ui/src/lib/core/src/components/breadcrumb/breadcrumb.component.spec.ts, packages/admin-ui/src/lib/core/src/providers/notification/notification.service.spec.ts, packages/admin-ui/src/lib/core/src/shared/components/data-table-2/data-table-search.component.ts, packages/admin-ui/src/lib/core/src/shared/components/page-title/page-title.component.ts, packages/admin-ui/tsconfig.json, packages/admin-ui/tsconfig.spec.json, packages/admin-ui/vite.config.ts
- Updates the Vitest setup and relevant files to run all tests for the `admin-ui` package.
- Initial work started by @michaelbromley 
📌 Always:
=> test: Fix unit tests with Vitest for admin-ui

packages/admin-ui/src/lib/marketing/src/components/promotion-list/promotion-list.component.html
Update the header text of Column Usage Limit which was incorrectly display as per-customer-limit
No
📌 Always:
- [/] I have added or updated test cases
- [/] I have updated the README if needed
=> Fix Incorrect Promotion Header Text

packages/core/src/config/order/default-order-process.ts
Fix floating promise & missed eventBus
no
=> fix(core): Fix floating promise & missed eventBus

packages/core/src/api/config/configure-graphql-module.ts
Enabling this functionality: https://github.com/nestjs/graphql/pull/2038
No
📌 Always:
=> feat: Enable inherit resolvers from interfaces

docs/docs/reference/typescript-api/events/event-types.md, packages/core/src/event-bus/events/order-line-event.ts, packages/core/src/service/helpers/order-modifier/order-modifier.ts
Publishing an Event for cancelling orderLine.
Issue: https://github.com/vendure-ecommerce/vendure/issues/2828
📌 Always:
=> feat(core): Add Event for Cancel OrderLine

docs/docs/guides/developer-guide/custom-fields/index.md, docs/docs/guides/developer-guide/strategies-configurable-operations/index.mdx
Minor corrections to "Custom Fields" and "Strategies & Configurable Operations" developer guides.
None
None
📌 Always:
=> docs: minor corrections to developer guides

packages/core/src/service/services/stock-movement.service.ts
Allow creation of fulfillment for order lines referencing deleted product variants. Closes #2434 
None
📌 Always:
=> fix(core): fulfillment creation with deleted product variants

packages/admin-ui/src/lib/core/src/shared/pipes/locale-date.pipe.spec.ts, packages/admin-ui/src/lib/core/src/shared/pipes/locale-date.pipe.ts
Fixes https://github.com/vendure-ecommerce/vendure/issues/2970
No
📌 Always:
=> chore: Respect the 24hours format in locale-date

packages/core/src/service/helpers/external-authentication/external-authentication.service.ts
this method has optional firstName and lastName in fields but required inside the method to create customer.
verified should bew optional but required in the config
nope
📌 Always:
=> fix(core): Make firstName and lastName required CreateCustomerAndUser

packages/admin-ui/src/lib/catalog/src/components/create-product-variant-dialog/create-product-variant-dialog.component.ts
fix(admin-ui): make sku optional in create-product-variant-dialog
- #2999 
N/A
N/A
📌 Always:
=> fix(admin-ui): Make sku optional in create-product-variant-dialog

packages/core/src/api/resolvers/entity/user-entity.resolver.ts
User Entity was missing the Roles field resolved
No
📌 Always:
=> fix(core): Roles were not resolved on User entity

packages/admin-ui/src/lib/core/src/components/app-shell/app-shell.component.html, packages/admin-ui/src/lib/core/src/providers/alerts/alerts.service.ts, packages/admin-ui/src/lib/core/src/providers/auth/auth.service.ts
=> fix(admin-ui): Unsubscribe from alerts when logging out

license/signatures/version1/cla.json, packages/core/src/config/index.ts, packages/core/src/config/tax/address-based-tax-zone-strategy.spec.ts, packages/core/src/config/tax/address-based-tax-zone-strategy.ts
Implemented address based tax zone strategy that determines tax zone based on the billing or shipping address of the order. Closes #2914
None.
📌 Always:
=> feat(vendure): Included address based tax zone strategy

docs/docs/reference/typescript-api/configuration/vendure-config.md, packages/core/src/config/vendure-config.ts
Small PR - Commit 7170e423908bbe852e31ef8c4835170e204e73c3 moved the location of `vendure-config.ts`. This PR adjusts sources to changes.
No
📌 Always:
=> docs: update `vendure-config.ts` reference

README.md
changed the current stable release to 3.x
📌 Always:
=> docs: changed the current stable release to 3.x

packages/asset-server-plugin/src/transform-image.ts
=> fix(on-fly-resize): Added rotate to handle EXIF

README.md
=> changed demo website

packages/elasticsearch-plugin/src/plugin.ts
=> changed the reference top shop-api

docs/docs/guides/developer-guide/dataloaders/index.md
Docs typo
No only docs
📌 Always:
=> [docs] fixed typo

docs/docs/guides/developer-guide/extend-graphql-api/index.md
Ran into this. Fixed it by checking out the source code. Docs would have saved me time, so I'll contribute.
No.
No.
📌 Always:
=> docs: Update extending graphql api

.github/workflows/build_and_test_branches.yml, .github/workflows/build_and_test_master.yml, .github/workflows/build_and_test_pr.yml, .github/workflows/publish_and_install_branches.yml, .github/workflows/publish_and_install_master.yml, .github/workflows/publish_and_install_pr.yml, README.md
- Updated README badges to reflect new workflow names.
- Added workflows for building and testing branches, master, and pull requests.
- Introduced publish and install workflows for branches, master, and pull requests.
- Ensured compatibility with multiple Node.js versions and various databases in CI processes.
None. 
📌 Always:
=> chore: Update README and split current workflows

.cursor/mcp.json, package-lock.json, packages/dashboard/package.json, packages/dashboard/src/components/data-table/data-table-column-header.tsx, packages/dashboard/src/components/data-table/data-table-faceted-filter.tsx, packages/dashboard/src/components/data-table/data-table.tsx, packages/dashboard/src/components/layout/nav-main.tsx, packages/dashboard/src/components/shared/paginated-list-data-table.tsx, packages/dashboard/src/components/ui/badge.tsx, packages/dashboard/src/components/ui/button.tsx, packages/dashboard/src/framework/defaults.ts, packages/dashboard/src/framework/page/list-page.tsx, packages/dashboard/src/graphql/graphql.ts, packages/dashboard/src/routeTree.gen.ts, packages/dashboard/src/routes/_authenticated/_system/components/payload-dialog.tsx, packages/dashboard/src/routes/_authenticated/_system/healthchecks.tsx, packages/dashboard/src/routes/_authenticated/_system/job-queue.graphql.ts, packages/dashboard/src/routes/_authenticated/_system/job-queue.tsx, packages/dashboard/src/styles.css, packages/dev-server/vite.config.mts
- Adds healthchecks view 
- Adds job queue view 
- Introduces new feature for the data table: Faceted Filters
=> feat(dashboard): Add system views 

packages/dashboard/index.html
Replaces the default Vite title tag
=> feat(dashboard): Enhance index.html with meta tags

packages/dashboard/src/app/routes/__root.tsx, packages/dashboard/src/app/routes/_authenticated/_administrators/administrators.tsx, packages/dashboard/src/app/routes/_authenticated/_channels/channels.tsx, packages/dashboard/src/app/routes/_authenticated/_collections/collections.tsx, packages/dashboard/src/app/routes/_authenticated/_countries/countries.tsx, packages/dashboard/src/app/routes/_authenticated/_customer-groups/customer-groups.tsx, packages/dashboard/src/app/routes/_authenticated/_customers/customers.tsx, packages/dashboard/src/app/routes/_authenticated/_facets/facets.tsx, packages/dashboard/src/app/routes/_authenticated/_payment-methods/payment-methods.tsx, packages/dashboard/src/app/routes/_authenticated/_product-variants/product-variants.tsx, packages/dashboard/src/app/routes/_authenticated/_products/products.tsx, packages/dashboard/src/app/routes/_authenticated/_promotions/promotions.tsx, packages/dashboard/src/app/routes/_authenticated/_roles/roles.tsx, packages/dashboard/src/app/routes/_authenticated/_sellers/sellers.tsx, packages/dashboard/src/app/routes/_authenticated/_shipping-methods/shipping-methods.tsx, packages/dashboard/src/app/routes/_authenticated/_stock-locations/stock-locations.tsx, packages/dashboard/src/app/routes/_authenticated/_tax-categories/tax-categories.tsx, packages/dashboard/src/app/routes/_authenticated/_tax-rates/tax-rates.tsx, packages/dashboard/src/app/routes/_authenticated/_zones/zones.tsx, packages/dashboard/src/lib/components/layout/app-layout.tsx, packages/dashboard/src/lib/components/layout/prerelease-popup.tsx, packages/dashboard/src/lib/components/shared/history-timeline/history-entry.tsx, packages/dashboard/src/lib/components/shared/history-timeline/history-note-input.tsx, packages/dashboard/src/lib/providers/user-settings.tsx
Fixing some UI issues in the dashboard
=> Dashboard fixes

package-lock.json, packages/dashboard/src/app/routes/_authenticated/index.tsx, packages/dashboard/src/app/styles.css
Fixes the broken layout of the widgets after window resize
=> fix(dashboard): Widgets layout on dashboard page after window resize

packages/dashboard/vite.config.mts, packages/dashboard/vite/utils/config-loader.ts
Attempting to debug test failure that only occurs in CI
=> chore(dashboard): Change logging for TS compilation errors

docs/docs/guides/developer-guide/importing-data/index.md
Adds a code example for the ProductVariantService that will: 
- Bootstrap a worker
- Create an admin context
- Call the service method
- Create an example Product Variant
- Handle the returned array of variants
- Reindex the search service afterward
Changes: docs/docs/guides/developer-guide/importing-data/index.md
📌 Always:
Closes:
[Missing example of ProductVariantService in importing data doc · Issue #3314 · vendure-ecommerce/vendure](https://github.com/vendure-ecommerce/vendure/issues/3314)
=> docs(core): Add example for ProductVariantService in the Custom populate scripts section

packages/core/src/plugin/plugin-utils.ts
Use proper template strings to add the basePath to the proxy target. 
Related to: https://github.com/vendure-ecommerce/vendure/pull/3507
Nope
📌 Always:
=> fix(admin-ui-plugin): proxy target template string

packages/core/src/api/resolvers/admin/product.resolver.ts
removed unused variable
No
📌 Always:
=> fix(ProductResolver): remove unused variable

CONTRIBUTING.md
=> docs: added guidelines for issue triage

.github/workflows/sync-jira.yml
My [scanning tool Gato-X](https://github.com/adnaneKhan/gato-x) picked up an issue title injection in the Jira sync workflow. This PR fixes it. Making a PR as the vulnerability is trivial to fix and exploitation would require a team member to first label an issue with `core-team.
```
.d8888b.         d8888 88888888888  .d88888b.         Y88b   d88P 
d88P  Y88b       d88888     888     d88P" "Y88b         Y88b d88P  
888    888      d88P888     888     888     888          Y88o88P   
888            d88P 888     888     888     888           Y888P    
888  88888    d88P  888     888     888     888           d888b    
888    888   d88P   888     888     888     888 888888   d88888b   
Y88b  d88P  d8888888888     888     Y88b. .d88P         d88P Y88b  
"Y8888P88 d88P     888     888 …
```
=> Safely use issue title variable

packages/core/e2e/order-interceptor.e2e-spec.ts, packages/core/src/service/services/order.service.ts
This PR updates `removeAllItemsFromOrder` so it now triggers the `willRemoveItemFromOrder` interceptor for each order line being removed, matching the behavior of single-line removal (`removeItemFromOrder`).
No.
📌 Always:
=> fix(core): Call `willRemoveItemFromOrder` in `removeAllItemsFromOrder` as well (#3578)

packages/core/src/api/common/validate-custom-field-value.spec.ts, packages/core/src/api/common/validate-custom-field-value.ts, packages/dashboard/src/lib/components/data-input/custom-field-list-input.tsx, packages/dashboard/src/lib/components/data-input/datetime-input.tsx, packages/dashboard/src/lib/components/data-input/default-relation-input.tsx, packages/dashboard/src/lib/components/data-input/index.ts, packages/dashboard/src/lib/components/data-input/relation-selector.tsx, packages/dashboard/src/lib/components/data-input/select-with-options.tsx, packages/dashboard/src/lib/components/data-input/struct-form-input.tsx, packages/dashboard/src/lib/components/shared/custom-fields-form.tsx, packages/dashboard/src/lib/components/shared/multi-select.tsx, packages/dashboard/src/lib/components/ui/form.tsx, packages/dashboard/src/lib/framework/form-engine/form-schema-tools.spec.ts, packages/dashboard/src/lib/framework/form-engine/form-schema-tools.ts, packages/dashboard/src/lib/framework/form-engine/use-generated-form.tsx, packages/dashboard/src/lib/framework/form-engine/utils.ts, packages/dashboard/src/lib/framework/layout-engine/page-layout.tsx, packages/dashboard/src/lib/framework/page/use-detail-page.ts, packages/dashboard/src/lib/lib/utils.ts
This PR will implement complete support in the Dashboard for all features of custom fields, including:
- default components for all data types
- validation
- support for lists including drag-drop reordering
- support for structs
- support for relations, with default selectors for all built-in entities
=> feat(dashboard): Dashboard custom field improvements

docs/src/css/components.css
Adds border, border radius and background to all images in the docs. 
📌 Always:
=> docs(core): Modify docs Codeblock copy to always visible and image borders
